//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshDeserialize;
use borsh::BorshSerialize;

pub const CLOSE_POOL_DISCRIMINATOR: [u8; 8] = [140, 189, 209, 23, 239, 62, 239, 11];

/// Accounts.
#[derive(Debug)]
pub struct ClosePool {
    pub admin: solana_pubkey::Pubkey,

    pub pool: solana_pubkey::Pubkey,

    pub swap_curve: solana_pubkey::Pubkey,

    pub pool_authority: solana_pubkey::Pubkey,

    pub token_a_mint: solana_pubkey::Pubkey,

    pub token_b_mint: solana_pubkey::Pubkey,

    pub token_a_vault: solana_pubkey::Pubkey,

    pub token_b_vault: solana_pubkey::Pubkey,

    pub pool_token_mint: solana_pubkey::Pubkey,

    pub token_a_fees_vault: solana_pubkey::Pubkey,

    pub token_b_fees_vault: solana_pubkey::Pubkey,
    /// Token program for the pool token mint
    pub pool_token_program: solana_pubkey::Pubkey,
    /// Token program for the token A mint
    pub token_a_token_program: solana_pubkey::Pubkey,
    /// Token program for the token B mint
    pub token_b_token_program: solana_pubkey::Pubkey,

    pub event_authority: solana_pubkey::Pubkey,

    pub program: solana_pubkey::Pubkey,
}

impl ClosePool {
    pub fn instruction(&self) -> solana_instruction::Instruction {
        self.instruction_with_remaining_accounts(&[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::vec_init_then_push)]
    pub fn instruction_with_remaining_accounts(
        &self,
        remaining_accounts: &[solana_instruction::AccountMeta],
    ) -> solana_instruction::Instruction {
        let mut accounts = Vec::with_capacity(16 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new(self.admin, true));
        accounts.push(solana_instruction::AccountMeta::new(self.pool, false));
        accounts.push(solana_instruction::AccountMeta::new(self.swap_curve, false));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.pool_authority,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.token_a_mint,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.token_b_mint,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.token_a_vault,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.token_b_vault,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.pool_token_mint,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.token_a_fees_vault,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.token_b_fees_vault,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.pool_token_program,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.token_a_token_program,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.token_b_token_program,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.event_authority,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.program,
            false,
        ));
        accounts.extend_from_slice(remaining_accounts);
        let data = ClosePoolInstructionData::new().try_to_vec().unwrap();

        solana_instruction::Instruction {
            program_id: crate::HYPERPLANE_ID,
            accounts,
            data,
        }
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct ClosePoolInstructionData {
    discriminator: [u8; 8],
}

impl ClosePoolInstructionData {
    pub fn new() -> Self {
        Self {
            discriminator: [140, 189, 209, 23, 239, 62, 239, 11],
        }
    }

    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
        borsh::to_vec(self)
    }
}

impl Default for ClosePoolInstructionData {
    fn default() -> Self {
        Self::new()
    }
}

/// Instruction builder for `ClosePool`.
///
/// ### Accounts:
///
///   0. `[writable, signer]` admin
///   1. `[writable]` pool
///   2. `[writable]` swap_curve
///   3. `[]` pool_authority
///   4. `[]` token_a_mint
///   5. `[]` token_b_mint
///   6. `[writable]` token_a_vault
///   7. `[writable]` token_b_vault
///   8. `[writable]` pool_token_mint
///   9. `[writable]` token_a_fees_vault
///   10. `[writable]` token_b_fees_vault
///   11. `[]` pool_token_program
///   12. `[]` token_a_token_program
///   13. `[]` token_b_token_program
///   14. `[]` event_authority
///   15. `[]` program
#[derive(Clone, Debug, Default)]
pub struct ClosePoolBuilder {
    admin: Option<solana_pubkey::Pubkey>,
    pool: Option<solana_pubkey::Pubkey>,
    swap_curve: Option<solana_pubkey::Pubkey>,
    pool_authority: Option<solana_pubkey::Pubkey>,
    token_a_mint: Option<solana_pubkey::Pubkey>,
    token_b_mint: Option<solana_pubkey::Pubkey>,
    token_a_vault: Option<solana_pubkey::Pubkey>,
    token_b_vault: Option<solana_pubkey::Pubkey>,
    pool_token_mint: Option<solana_pubkey::Pubkey>,
    token_a_fees_vault: Option<solana_pubkey::Pubkey>,
    token_b_fees_vault: Option<solana_pubkey::Pubkey>,
    pool_token_program: Option<solana_pubkey::Pubkey>,
    token_a_token_program: Option<solana_pubkey::Pubkey>,
    token_b_token_program: Option<solana_pubkey::Pubkey>,
    event_authority: Option<solana_pubkey::Pubkey>,
    program: Option<solana_pubkey::Pubkey>,
    __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl ClosePoolBuilder {
    pub fn new() -> Self {
        Self::default()
    }
    #[inline(always)]
    pub fn admin(&mut self, admin: solana_pubkey::Pubkey) -> &mut Self {
        self.admin = Some(admin);
        self
    }
    #[inline(always)]
    pub fn pool(&mut self, pool: solana_pubkey::Pubkey) -> &mut Self {
        self.pool = Some(pool);
        self
    }
    #[inline(always)]
    pub fn swap_curve(&mut self, swap_curve: solana_pubkey::Pubkey) -> &mut Self {
        self.swap_curve = Some(swap_curve);
        self
    }
    #[inline(always)]
    pub fn pool_authority(&mut self, pool_authority: solana_pubkey::Pubkey) -> &mut Self {
        self.pool_authority = Some(pool_authority);
        self
    }
    #[inline(always)]
    pub fn token_a_mint(&mut self, token_a_mint: solana_pubkey::Pubkey) -> &mut Self {
        self.token_a_mint = Some(token_a_mint);
        self
    }
    #[inline(always)]
    pub fn token_b_mint(&mut self, token_b_mint: solana_pubkey::Pubkey) -> &mut Self {
        self.token_b_mint = Some(token_b_mint);
        self
    }
    #[inline(always)]
    pub fn token_a_vault(&mut self, token_a_vault: solana_pubkey::Pubkey) -> &mut Self {
        self.token_a_vault = Some(token_a_vault);
        self
    }
    #[inline(always)]
    pub fn token_b_vault(&mut self, token_b_vault: solana_pubkey::Pubkey) -> &mut Self {
        self.token_b_vault = Some(token_b_vault);
        self
    }
    #[inline(always)]
    pub fn pool_token_mint(&mut self, pool_token_mint: solana_pubkey::Pubkey) -> &mut Self {
        self.pool_token_mint = Some(pool_token_mint);
        self
    }
    #[inline(always)]
    pub fn token_a_fees_vault(&mut self, token_a_fees_vault: solana_pubkey::Pubkey) -> &mut Self {
        self.token_a_fees_vault = Some(token_a_fees_vault);
        self
    }
    #[inline(always)]
    pub fn token_b_fees_vault(&mut self, token_b_fees_vault: solana_pubkey::Pubkey) -> &mut Self {
        self.token_b_fees_vault = Some(token_b_fees_vault);
        self
    }
    /// Token program for the pool token mint
    #[inline(always)]
    pub fn pool_token_program(&mut self, pool_token_program: solana_pubkey::Pubkey) -> &mut Self {
        self.pool_token_program = Some(pool_token_program);
        self
    }
    /// Token program for the token A mint
    #[inline(always)]
    pub fn token_a_token_program(
        &mut self,
        token_a_token_program: solana_pubkey::Pubkey,
    ) -> &mut Self {
        self.token_a_token_program = Some(token_a_token_program);
        self
    }
    /// Token program for the token B mint
    #[inline(always)]
    pub fn token_b_token_program(
        &mut self,
        token_b_token_program: solana_pubkey::Pubkey,
    ) -> &mut Self {
        self.token_b_token_program = Some(token_b_token_program);
        self
    }
    #[inline(always)]
    pub fn event_authority(&mut self, event_authority: solana_pubkey::Pubkey) -> &mut Self {
        self.event_authority = Some(event_authority);
        self
    }
    #[inline(always)]
    pub fn program(&mut self, program: solana_pubkey::Pubkey) -> &mut Self {
        self.program = Some(program);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
        self.__remaining_accounts.push(account);
        self
    }
    /// Add additional accounts to the instruction.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[solana_instruction::AccountMeta],
    ) -> &mut Self {
        self.__remaining_accounts.extend_from_slice(accounts);
        self
    }
    #[allow(clippy::clone_on_copy)]
    pub fn instruction(&self) -> solana_instruction::Instruction {
        let accounts = ClosePool {
            admin: self.admin.expect("admin is not set"),
            pool: self.pool.expect("pool is not set"),
            swap_curve: self.swap_curve.expect("swap_curve is not set"),
            pool_authority: self.pool_authority.expect("pool_authority is not set"),
            token_a_mint: self.token_a_mint.expect("token_a_mint is not set"),
            token_b_mint: self.token_b_mint.expect("token_b_mint is not set"),
            token_a_vault: self.token_a_vault.expect("token_a_vault is not set"),
            token_b_vault: self.token_b_vault.expect("token_b_vault is not set"),
            pool_token_mint: self.pool_token_mint.expect("pool_token_mint is not set"),
            token_a_fees_vault: self
                .token_a_fees_vault
                .expect("token_a_fees_vault is not set"),
            token_b_fees_vault: self
                .token_b_fees_vault
                .expect("token_b_fees_vault is not set"),
            pool_token_program: self
                .pool_token_program
                .expect("pool_token_program is not set"),
            token_a_token_program: self
                .token_a_token_program
                .expect("token_a_token_program is not set"),
            token_b_token_program: self
                .token_b_token_program
                .expect("token_b_token_program is not set"),
            event_authority: self.event_authority.expect("event_authority is not set"),
            program: self.program.expect("program is not set"),
        };

        accounts.instruction_with_remaining_accounts(&self.__remaining_accounts)
    }
}

/// `close_pool` CPI accounts.
pub struct ClosePoolCpiAccounts<'a, 'b> {
    pub admin: &'b solana_account_info::AccountInfo<'a>,

    pub pool: &'b solana_account_info::AccountInfo<'a>,

    pub swap_curve: &'b solana_account_info::AccountInfo<'a>,

    pub pool_authority: &'b solana_account_info::AccountInfo<'a>,

    pub token_a_mint: &'b solana_account_info::AccountInfo<'a>,

    pub token_b_mint: &'b solana_account_info::AccountInfo<'a>,

    pub token_a_vault: &'b solana_account_info::AccountInfo<'a>,

    pub token_b_vault: &'b solana_account_info::AccountInfo<'a>,

    pub pool_token_mint: &'b solana_account_info::AccountInfo<'a>,

    pub token_a_fees_vault: &'b solana_account_info::AccountInfo<'a>,

    pub token_b_fees_vault: &'b solana_account_info::AccountInfo<'a>,
    /// Token program for the pool token mint
    pub pool_token_program: &'b solana_account_info::AccountInfo<'a>,
    /// Token program for the token A mint
    pub token_a_token_program: &'b solana_account_info::AccountInfo<'a>,
    /// Token program for the token B mint
    pub token_b_token_program: &'b solana_account_info::AccountInfo<'a>,

    pub event_authority: &'b solana_account_info::AccountInfo<'a>,

    pub program: &'b solana_account_info::AccountInfo<'a>,
}

/// `close_pool` CPI instruction.
pub struct ClosePoolCpi<'a, 'b> {
    /// The program to invoke.
    pub __program: &'b solana_account_info::AccountInfo<'a>,

    pub admin: &'b solana_account_info::AccountInfo<'a>,

    pub pool: &'b solana_account_info::AccountInfo<'a>,

    pub swap_curve: &'b solana_account_info::AccountInfo<'a>,

    pub pool_authority: &'b solana_account_info::AccountInfo<'a>,

    pub token_a_mint: &'b solana_account_info::AccountInfo<'a>,

    pub token_b_mint: &'b solana_account_info::AccountInfo<'a>,

    pub token_a_vault: &'b solana_account_info::AccountInfo<'a>,

    pub token_b_vault: &'b solana_account_info::AccountInfo<'a>,

    pub pool_token_mint: &'b solana_account_info::AccountInfo<'a>,

    pub token_a_fees_vault: &'b solana_account_info::AccountInfo<'a>,

    pub token_b_fees_vault: &'b solana_account_info::AccountInfo<'a>,
    /// Token program for the pool token mint
    pub pool_token_program: &'b solana_account_info::AccountInfo<'a>,
    /// Token program for the token A mint
    pub token_a_token_program: &'b solana_account_info::AccountInfo<'a>,
    /// Token program for the token B mint
    pub token_b_token_program: &'b solana_account_info::AccountInfo<'a>,

    pub event_authority: &'b solana_account_info::AccountInfo<'a>,

    pub program: &'b solana_account_info::AccountInfo<'a>,
}

impl<'a, 'b> ClosePoolCpi<'a, 'b> {
    pub fn new(
        program: &'b solana_account_info::AccountInfo<'a>,
        accounts: ClosePoolCpiAccounts<'a, 'b>,
    ) -> Self {
        Self {
            __program: program,
            admin: accounts.admin,
            pool: accounts.pool,
            swap_curve: accounts.swap_curve,
            pool_authority: accounts.pool_authority,
            token_a_mint: accounts.token_a_mint,
            token_b_mint: accounts.token_b_mint,
            token_a_vault: accounts.token_a_vault,
            token_b_vault: accounts.token_b_vault,
            pool_token_mint: accounts.pool_token_mint,
            token_a_fees_vault: accounts.token_a_fees_vault,
            token_b_fees_vault: accounts.token_b_fees_vault,
            pool_token_program: accounts.pool_token_program,
            token_a_token_program: accounts.token_a_token_program,
            token_b_token_program: accounts.token_b_token_program,
            event_authority: accounts.event_authority,
            program: accounts.program,
        }
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], &[])
    }
    #[inline(always)]
    pub fn invoke_with_remaining_accounts(
        &self,
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
    }
    #[inline(always)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed_with_remaining_accounts(
        &self,
        signers_seeds: &[&[&[u8]]],
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        let mut accounts = Vec::with_capacity(16 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new(*self.admin.key, true));
        accounts.push(solana_instruction::AccountMeta::new(*self.pool.key, false));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.swap_curve.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.pool_authority.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.token_a_mint.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.token_b_mint.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.token_a_vault.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.token_b_vault.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.pool_token_mint.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.token_a_fees_vault.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.token_b_fees_vault.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.pool_token_program.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.token_a_token_program.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.token_b_token_program.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.event_authority.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.program.key,
            false,
        ));
        remaining_accounts.iter().for_each(|remaining_account| {
            accounts.push(solana_instruction::AccountMeta {
                pubkey: *remaining_account.0.key,
                is_signer: remaining_account.1,
                is_writable: remaining_account.2,
            })
        });
        let data = ClosePoolInstructionData::new().try_to_vec().unwrap();

        let instruction = solana_instruction::Instruction {
            program_id: crate::HYPERPLANE_ID,
            accounts,
            data,
        };
        let mut account_infos = Vec::with_capacity(17 + remaining_accounts.len());
        account_infos.push(self.__program.clone());
        account_infos.push(self.admin.clone());
        account_infos.push(self.pool.clone());
        account_infos.push(self.swap_curve.clone());
        account_infos.push(self.pool_authority.clone());
        account_infos.push(self.token_a_mint.clone());
        account_infos.push(self.token_b_mint.clone());
        account_infos.push(self.token_a_vault.clone());
        account_infos.push(self.token_b_vault.clone());
        account_infos.push(self.pool_token_mint.clone());
        account_infos.push(self.token_a_fees_vault.clone());
        account_infos.push(self.token_b_fees_vault.clone());
        account_infos.push(self.pool_token_program.clone());
        account_infos.push(self.token_a_token_program.clone());
        account_infos.push(self.token_b_token_program.clone());
        account_infos.push(self.event_authority.clone());
        account_infos.push(self.program.clone());
        remaining_accounts
            .iter()
            .for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

        if signers_seeds.is_empty() {
            solana_cpi::invoke(&instruction, &account_infos)
        } else {
            solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
        }
    }
}

/// Instruction builder for `ClosePool` via CPI.
///
/// ### Accounts:
///
///   0. `[writable, signer]` admin
///   1. `[writable]` pool
///   2. `[writable]` swap_curve
///   3. `[]` pool_authority
///   4. `[]` token_a_mint
///   5. `[]` token_b_mint
///   6. `[writable]` token_a_vault
///   7. `[writable]` token_b_vault
///   8. `[writable]` pool_token_mint
///   9. `[writable]` token_a_fees_vault
///   10. `[writable]` token_b_fees_vault
///   11. `[]` pool_token_program
///   12. `[]` token_a_token_program
///   13. `[]` token_b_token_program
///   14. `[]` event_authority
///   15. `[]` program
#[derive(Clone, Debug)]
pub struct ClosePoolCpiBuilder<'a, 'b> {
    instruction: Box<ClosePoolCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> ClosePoolCpiBuilder<'a, 'b> {
    pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
        let instruction = Box::new(ClosePoolCpiBuilderInstruction {
            __program: program,
            admin: None,
            pool: None,
            swap_curve: None,
            pool_authority: None,
            token_a_mint: None,
            token_b_mint: None,
            token_a_vault: None,
            token_b_vault: None,
            pool_token_mint: None,
            token_a_fees_vault: None,
            token_b_fees_vault: None,
            pool_token_program: None,
            token_a_token_program: None,
            token_b_token_program: None,
            event_authority: None,
            program: None,
            __remaining_accounts: Vec::new(),
        });
        Self { instruction }
    }
    #[inline(always)]
    pub fn admin(&mut self, admin: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.admin = Some(admin);
        self
    }
    #[inline(always)]
    pub fn pool(&mut self, pool: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.pool = Some(pool);
        self
    }
    #[inline(always)]
    pub fn swap_curve(
        &mut self,
        swap_curve: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.swap_curve = Some(swap_curve);
        self
    }
    #[inline(always)]
    pub fn pool_authority(
        &mut self,
        pool_authority: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.pool_authority = Some(pool_authority);
        self
    }
    #[inline(always)]
    pub fn token_a_mint(
        &mut self,
        token_a_mint: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.token_a_mint = Some(token_a_mint);
        self
    }
    #[inline(always)]
    pub fn token_b_mint(
        &mut self,
        token_b_mint: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.token_b_mint = Some(token_b_mint);
        self
    }
    #[inline(always)]
    pub fn token_a_vault(
        &mut self,
        token_a_vault: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.token_a_vault = Some(token_a_vault);
        self
    }
    #[inline(always)]
    pub fn token_b_vault(
        &mut self,
        token_b_vault: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.token_b_vault = Some(token_b_vault);
        self
    }
    #[inline(always)]
    pub fn pool_token_mint(
        &mut self,
        pool_token_mint: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.pool_token_mint = Some(pool_token_mint);
        self
    }
    #[inline(always)]
    pub fn token_a_fees_vault(
        &mut self,
        token_a_fees_vault: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.token_a_fees_vault = Some(token_a_fees_vault);
        self
    }
    #[inline(always)]
    pub fn token_b_fees_vault(
        &mut self,
        token_b_fees_vault: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.token_b_fees_vault = Some(token_b_fees_vault);
        self
    }
    /// Token program for the pool token mint
    #[inline(always)]
    pub fn pool_token_program(
        &mut self,
        pool_token_program: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.pool_token_program = Some(pool_token_program);
        self
    }
    /// Token program for the token A mint
    #[inline(always)]
    pub fn token_a_token_program(
        &mut self,
        token_a_token_program: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.token_a_token_program = Some(token_a_token_program);
        self
    }
    /// Token program for the token B mint
    #[inline(always)]
    pub fn token_b_token_program(
        &mut self,
        token_b_token_program: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.token_b_token_program = Some(token_b_token_program);
        self
    }
    #[inline(always)]
    pub fn event_authority(
        &mut self,
        event_authority: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.event_authority = Some(event_authority);
        self
    }
    #[inline(always)]
    pub fn program(&mut self, program: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.program = Some(program);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(
        &mut self,
        account: &'b solana_account_info::AccountInfo<'a>,
        is_writable: bool,
        is_signer: bool,
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .push((account, is_writable, is_signer));
        self
    }
    /// Add additional accounts to the instruction.
    ///
    /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
    /// and a `bool` indicating whether the account is a signer or not.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .extend_from_slice(accounts);
        self
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed(&[])
    }
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        let instruction = ClosePoolCpi {
            __program: self.instruction.__program,

            admin: self.instruction.admin.expect("admin is not set"),

            pool: self.instruction.pool.expect("pool is not set"),

            swap_curve: self.instruction.swap_curve.expect("swap_curve is not set"),

            pool_authority: self
                .instruction
                .pool_authority
                .expect("pool_authority is not set"),

            token_a_mint: self
                .instruction
                .token_a_mint
                .expect("token_a_mint is not set"),

            token_b_mint: self
                .instruction
                .token_b_mint
                .expect("token_b_mint is not set"),

            token_a_vault: self
                .instruction
                .token_a_vault
                .expect("token_a_vault is not set"),

            token_b_vault: self
                .instruction
                .token_b_vault
                .expect("token_b_vault is not set"),

            pool_token_mint: self
                .instruction
                .pool_token_mint
                .expect("pool_token_mint is not set"),

            token_a_fees_vault: self
                .instruction
                .token_a_fees_vault
                .expect("token_a_fees_vault is not set"),

            token_b_fees_vault: self
                .instruction
                .token_b_fees_vault
                .expect("token_b_fees_vault is not set"),

            pool_token_program: self
                .instruction
                .pool_token_program
                .expect("pool_token_program is not set"),

            token_a_token_program: self
                .instruction
                .token_a_token_program
                .expect("token_a_token_program is not set"),

            token_b_token_program: self
                .instruction
                .token_b_token_program
                .expect("token_b_token_program is not set"),

            event_authority: self
                .instruction
                .event_authority
                .expect("event_authority is not set"),

            program: self.instruction.program.expect("program is not set"),
        };
        instruction.invoke_signed_with_remaining_accounts(
            signers_seeds,
            &self.instruction.__remaining_accounts,
        )
    }
}

#[derive(Clone, Debug)]
struct ClosePoolCpiBuilderInstruction<'a, 'b> {
    __program: &'b solana_account_info::AccountInfo<'a>,
    admin: Option<&'b solana_account_info::AccountInfo<'a>>,
    pool: Option<&'b solana_account_info::AccountInfo<'a>>,
    swap_curve: Option<&'b solana_account_info::AccountInfo<'a>>,
    pool_authority: Option<&'b solana_account_info::AccountInfo<'a>>,
    token_a_mint: Option<&'b solana_account_info::AccountInfo<'a>>,
    token_b_mint: Option<&'b solana_account_info::AccountInfo<'a>>,
    token_a_vault: Option<&'b solana_account_info::AccountInfo<'a>>,
    token_b_vault: Option<&'b solana_account_info::AccountInfo<'a>>,
    pool_token_mint: Option<&'b solana_account_info::AccountInfo<'a>>,
    token_a_fees_vault: Option<&'b solana_account_info::AccountInfo<'a>>,
    token_b_fees_vault: Option<&'b solana_account_info::AccountInfo<'a>>,
    pool_token_program: Option<&'b solana_account_info::AccountInfo<'a>>,
    token_a_token_program: Option<&'b solana_account_info::AccountInfo<'a>>,
    token_b_token_program: Option<&'b solana_account_info::AccountInfo<'a>>,
    event_authority: Option<&'b solana_account_info::AccountInfo<'a>>,
    program: Option<&'b solana_account_info::AccountInfo<'a>>,
    /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
    __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}
