//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshDeserialize;
use borsh::BorshSerialize;

pub const DEPOSIT_DISCRIMINATOR: [u8; 8] = [242, 35, 198, 137, 82, 225, 242, 182];

/// Accounts.
#[derive(Debug)]
pub struct Deposit {
    pub admin: solana_pubkey::Pubkey,

    pub pool: solana_pubkey::Pubkey,

    pub swap_curve: solana_pubkey::Pubkey,

    pub pool_authority: solana_pubkey::Pubkey,

    pub token_a_mint: solana_pubkey::Pubkey,

    pub token_b_mint: solana_pubkey::Pubkey,

    pub token_a_vault: solana_pubkey::Pubkey,

    pub token_b_vault: solana_pubkey::Pubkey,

    pub pool_token_mint: solana_pubkey::Pubkey,
    /// Signer's token A token account
    pub token_a_user_ata: solana_pubkey::Pubkey,
    /// Signer's token B token account
    pub token_b_user_ata: solana_pubkey::Pubkey,
    /// Signer's pool token account
    pub pool_token_user_ata: solana_pubkey::Pubkey,
    /// Token program for the pool token mint
    pub pool_token_program: solana_pubkey::Pubkey,
    /// Token program for the source mint
    pub token_a_token_program: solana_pubkey::Pubkey,
    /// Token program for the destination mint
    pub token_b_token_program: solana_pubkey::Pubkey,

    pub event_authority: solana_pubkey::Pubkey,

    pub program: solana_pubkey::Pubkey,
}

impl Deposit {
    pub fn instruction(&self, args: DepositInstructionArgs) -> solana_instruction::Instruction {
        self.instruction_with_remaining_accounts(args, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::vec_init_then_push)]
    pub fn instruction_with_remaining_accounts(
        &self,
        args: DepositInstructionArgs,
        remaining_accounts: &[solana_instruction::AccountMeta],
    ) -> solana_instruction::Instruction {
        let mut accounts = Vec::with_capacity(17 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.admin, true,
        ));
        accounts.push(solana_instruction::AccountMeta::new(self.pool, false));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.swap_curve,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.pool_authority,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.token_a_mint,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.token_b_mint,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.token_a_vault,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.token_b_vault,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.pool_token_mint,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.token_a_user_ata,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.token_b_user_ata,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.pool_token_user_ata,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.pool_token_program,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.token_a_token_program,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.token_b_token_program,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.event_authority,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.program,
            false,
        ));
        accounts.extend_from_slice(remaining_accounts);
        let mut data = DepositInstructionData::new().try_to_vec().unwrap();
        let mut args = args.try_to_vec().unwrap();
        data.append(&mut args);

        solana_instruction::Instruction {
            program_id: crate::KDEX_ID,
            accounts,
            data,
        }
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct DepositInstructionData {
    discriminator: [u8; 8],
}

impl DepositInstructionData {
    pub fn new() -> Self {
        Self {
            discriminator: [242, 35, 198, 137, 82, 225, 242, 182],
        }
    }

    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
        borsh::to_vec(self)
    }
}

impl Default for DepositInstructionData {
    fn default() -> Self {
        Self::new()
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct DepositInstructionArgs {
    pub pool_token_amount: u64,
    pub maximum_token_a_amount: u64,
    pub maximum_token_b_amount: u64,
}

impl DepositInstructionArgs {
    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
        borsh::to_vec(self)
    }
}

/// Instruction builder for `Deposit`.
///
/// ### Accounts:
///
///   0. `[signer]` admin
///   1. `[writable]` pool
///   2. `[]` swap_curve
///   3. `[]` pool_authority
///   4. `[]` token_a_mint
///   5. `[]` token_b_mint
///   6. `[writable]` token_a_vault
///   7. `[writable]` token_b_vault
///   8. `[writable]` pool_token_mint
///   9. `[writable]` token_a_user_ata
///   10. `[writable]` token_b_user_ata
///   11. `[writable]` pool_token_user_ata
///   12. `[]` pool_token_program
///   13. `[]` token_a_token_program
///   14. `[]` token_b_token_program
///   15. `[]` event_authority
///   16. `[]` program
#[derive(Clone, Debug, Default)]
pub struct DepositBuilder {
    admin: Option<solana_pubkey::Pubkey>,
    pool: Option<solana_pubkey::Pubkey>,
    swap_curve: Option<solana_pubkey::Pubkey>,
    pool_authority: Option<solana_pubkey::Pubkey>,
    token_a_mint: Option<solana_pubkey::Pubkey>,
    token_b_mint: Option<solana_pubkey::Pubkey>,
    token_a_vault: Option<solana_pubkey::Pubkey>,
    token_b_vault: Option<solana_pubkey::Pubkey>,
    pool_token_mint: Option<solana_pubkey::Pubkey>,
    token_a_user_ata: Option<solana_pubkey::Pubkey>,
    token_b_user_ata: Option<solana_pubkey::Pubkey>,
    pool_token_user_ata: Option<solana_pubkey::Pubkey>,
    pool_token_program: Option<solana_pubkey::Pubkey>,
    token_a_token_program: Option<solana_pubkey::Pubkey>,
    token_b_token_program: Option<solana_pubkey::Pubkey>,
    event_authority: Option<solana_pubkey::Pubkey>,
    program: Option<solana_pubkey::Pubkey>,
    pool_token_amount: Option<u64>,
    maximum_token_a_amount: Option<u64>,
    maximum_token_b_amount: Option<u64>,
    __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl DepositBuilder {
    pub fn new() -> Self {
        Self::default()
    }
    #[inline(always)]
    pub fn admin(&mut self, admin: solana_pubkey::Pubkey) -> &mut Self {
        self.admin = Some(admin);
        self
    }
    #[inline(always)]
    pub fn pool(&mut self, pool: solana_pubkey::Pubkey) -> &mut Self {
        self.pool = Some(pool);
        self
    }
    #[inline(always)]
    pub fn swap_curve(&mut self, swap_curve: solana_pubkey::Pubkey) -> &mut Self {
        self.swap_curve = Some(swap_curve);
        self
    }
    #[inline(always)]
    pub fn pool_authority(&mut self, pool_authority: solana_pubkey::Pubkey) -> &mut Self {
        self.pool_authority = Some(pool_authority);
        self
    }
    #[inline(always)]
    pub fn token_a_mint(&mut self, token_a_mint: solana_pubkey::Pubkey) -> &mut Self {
        self.token_a_mint = Some(token_a_mint);
        self
    }
    #[inline(always)]
    pub fn token_b_mint(&mut self, token_b_mint: solana_pubkey::Pubkey) -> &mut Self {
        self.token_b_mint = Some(token_b_mint);
        self
    }
    #[inline(always)]
    pub fn token_a_vault(&mut self, token_a_vault: solana_pubkey::Pubkey) -> &mut Self {
        self.token_a_vault = Some(token_a_vault);
        self
    }
    #[inline(always)]
    pub fn token_b_vault(&mut self, token_b_vault: solana_pubkey::Pubkey) -> &mut Self {
        self.token_b_vault = Some(token_b_vault);
        self
    }
    #[inline(always)]
    pub fn pool_token_mint(&mut self, pool_token_mint: solana_pubkey::Pubkey) -> &mut Self {
        self.pool_token_mint = Some(pool_token_mint);
        self
    }
    /// Signer's token A token account
    #[inline(always)]
    pub fn token_a_user_ata(&mut self, token_a_user_ata: solana_pubkey::Pubkey) -> &mut Self {
        self.token_a_user_ata = Some(token_a_user_ata);
        self
    }
    /// Signer's token B token account
    #[inline(always)]
    pub fn token_b_user_ata(&mut self, token_b_user_ata: solana_pubkey::Pubkey) -> &mut Self {
        self.token_b_user_ata = Some(token_b_user_ata);
        self
    }
    /// Signer's pool token account
    #[inline(always)]
    pub fn pool_token_user_ata(&mut self, pool_token_user_ata: solana_pubkey::Pubkey) -> &mut Self {
        self.pool_token_user_ata = Some(pool_token_user_ata);
        self
    }
    /// Token program for the pool token mint
    #[inline(always)]
    pub fn pool_token_program(&mut self, pool_token_program: solana_pubkey::Pubkey) -> &mut Self {
        self.pool_token_program = Some(pool_token_program);
        self
    }
    /// Token program for the source mint
    #[inline(always)]
    pub fn token_a_token_program(
        &mut self,
        token_a_token_program: solana_pubkey::Pubkey,
    ) -> &mut Self {
        self.token_a_token_program = Some(token_a_token_program);
        self
    }
    /// Token program for the destination mint
    #[inline(always)]
    pub fn token_b_token_program(
        &mut self,
        token_b_token_program: solana_pubkey::Pubkey,
    ) -> &mut Self {
        self.token_b_token_program = Some(token_b_token_program);
        self
    }
    #[inline(always)]
    pub fn event_authority(&mut self, event_authority: solana_pubkey::Pubkey) -> &mut Self {
        self.event_authority = Some(event_authority);
        self
    }
    #[inline(always)]
    pub fn program(&mut self, program: solana_pubkey::Pubkey) -> &mut Self {
        self.program = Some(program);
        self
    }
    #[inline(always)]
    pub fn pool_token_amount(&mut self, pool_token_amount: u64) -> &mut Self {
        self.pool_token_amount = Some(pool_token_amount);
        self
    }
    #[inline(always)]
    pub fn maximum_token_a_amount(&mut self, maximum_token_a_amount: u64) -> &mut Self {
        self.maximum_token_a_amount = Some(maximum_token_a_amount);
        self
    }
    #[inline(always)]
    pub fn maximum_token_b_amount(&mut self, maximum_token_b_amount: u64) -> &mut Self {
        self.maximum_token_b_amount = Some(maximum_token_b_amount);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
        self.__remaining_accounts.push(account);
        self
    }
    /// Add additional accounts to the instruction.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[solana_instruction::AccountMeta],
    ) -> &mut Self {
        self.__remaining_accounts.extend_from_slice(accounts);
        self
    }
    #[allow(clippy::clone_on_copy)]
    pub fn instruction(&self) -> solana_instruction::Instruction {
        let accounts = Deposit {
            admin: self.admin.expect("admin is not set"),
            pool: self.pool.expect("pool is not set"),
            swap_curve: self.swap_curve.expect("swap_curve is not set"),
            pool_authority: self.pool_authority.expect("pool_authority is not set"),
            token_a_mint: self.token_a_mint.expect("token_a_mint is not set"),
            token_b_mint: self.token_b_mint.expect("token_b_mint is not set"),
            token_a_vault: self.token_a_vault.expect("token_a_vault is not set"),
            token_b_vault: self.token_b_vault.expect("token_b_vault is not set"),
            pool_token_mint: self.pool_token_mint.expect("pool_token_mint is not set"),
            token_a_user_ata: self.token_a_user_ata.expect("token_a_user_ata is not set"),
            token_b_user_ata: self.token_b_user_ata.expect("token_b_user_ata is not set"),
            pool_token_user_ata: self
                .pool_token_user_ata
                .expect("pool_token_user_ata is not set"),
            pool_token_program: self
                .pool_token_program
                .expect("pool_token_program is not set"),
            token_a_token_program: self
                .token_a_token_program
                .expect("token_a_token_program is not set"),
            token_b_token_program: self
                .token_b_token_program
                .expect("token_b_token_program is not set"),
            event_authority: self.event_authority.expect("event_authority is not set"),
            program: self.program.expect("program is not set"),
        };
        let args = DepositInstructionArgs {
            pool_token_amount: self
                .pool_token_amount
                .clone()
                .expect("pool_token_amount is not set"),
            maximum_token_a_amount: self
                .maximum_token_a_amount
                .clone()
                .expect("maximum_token_a_amount is not set"),
            maximum_token_b_amount: self
                .maximum_token_b_amount
                .clone()
                .expect("maximum_token_b_amount is not set"),
        };

        accounts.instruction_with_remaining_accounts(args, &self.__remaining_accounts)
    }
}

/// `deposit` CPI accounts.
pub struct DepositCpiAccounts<'a, 'b> {
    pub admin: &'b solana_account_info::AccountInfo<'a>,

    pub pool: &'b solana_account_info::AccountInfo<'a>,

    pub swap_curve: &'b solana_account_info::AccountInfo<'a>,

    pub pool_authority: &'b solana_account_info::AccountInfo<'a>,

    pub token_a_mint: &'b solana_account_info::AccountInfo<'a>,

    pub token_b_mint: &'b solana_account_info::AccountInfo<'a>,

    pub token_a_vault: &'b solana_account_info::AccountInfo<'a>,

    pub token_b_vault: &'b solana_account_info::AccountInfo<'a>,

    pub pool_token_mint: &'b solana_account_info::AccountInfo<'a>,
    /// Signer's token A token account
    pub token_a_user_ata: &'b solana_account_info::AccountInfo<'a>,
    /// Signer's token B token account
    pub token_b_user_ata: &'b solana_account_info::AccountInfo<'a>,
    /// Signer's pool token account
    pub pool_token_user_ata: &'b solana_account_info::AccountInfo<'a>,
    /// Token program for the pool token mint
    pub pool_token_program: &'b solana_account_info::AccountInfo<'a>,
    /// Token program for the source mint
    pub token_a_token_program: &'b solana_account_info::AccountInfo<'a>,
    /// Token program for the destination mint
    pub token_b_token_program: &'b solana_account_info::AccountInfo<'a>,

    pub event_authority: &'b solana_account_info::AccountInfo<'a>,

    pub program: &'b solana_account_info::AccountInfo<'a>,
}

/// `deposit` CPI instruction.
pub struct DepositCpi<'a, 'b> {
    /// The program to invoke.
    pub __program: &'b solana_account_info::AccountInfo<'a>,

    pub admin: &'b solana_account_info::AccountInfo<'a>,

    pub pool: &'b solana_account_info::AccountInfo<'a>,

    pub swap_curve: &'b solana_account_info::AccountInfo<'a>,

    pub pool_authority: &'b solana_account_info::AccountInfo<'a>,

    pub token_a_mint: &'b solana_account_info::AccountInfo<'a>,

    pub token_b_mint: &'b solana_account_info::AccountInfo<'a>,

    pub token_a_vault: &'b solana_account_info::AccountInfo<'a>,

    pub token_b_vault: &'b solana_account_info::AccountInfo<'a>,

    pub pool_token_mint: &'b solana_account_info::AccountInfo<'a>,
    /// Signer's token A token account
    pub token_a_user_ata: &'b solana_account_info::AccountInfo<'a>,
    /// Signer's token B token account
    pub token_b_user_ata: &'b solana_account_info::AccountInfo<'a>,
    /// Signer's pool token account
    pub pool_token_user_ata: &'b solana_account_info::AccountInfo<'a>,
    /// Token program for the pool token mint
    pub pool_token_program: &'b solana_account_info::AccountInfo<'a>,
    /// Token program for the source mint
    pub token_a_token_program: &'b solana_account_info::AccountInfo<'a>,
    /// Token program for the destination mint
    pub token_b_token_program: &'b solana_account_info::AccountInfo<'a>,

    pub event_authority: &'b solana_account_info::AccountInfo<'a>,

    pub program: &'b solana_account_info::AccountInfo<'a>,
    /// The arguments for the instruction.
    pub __args: DepositInstructionArgs,
}

impl<'a, 'b> DepositCpi<'a, 'b> {
    pub fn new(
        program: &'b solana_account_info::AccountInfo<'a>,
        accounts: DepositCpiAccounts<'a, 'b>,
        args: DepositInstructionArgs,
    ) -> Self {
        Self {
            __program: program,
            admin: accounts.admin,
            pool: accounts.pool,
            swap_curve: accounts.swap_curve,
            pool_authority: accounts.pool_authority,
            token_a_mint: accounts.token_a_mint,
            token_b_mint: accounts.token_b_mint,
            token_a_vault: accounts.token_a_vault,
            token_b_vault: accounts.token_b_vault,
            pool_token_mint: accounts.pool_token_mint,
            token_a_user_ata: accounts.token_a_user_ata,
            token_b_user_ata: accounts.token_b_user_ata,
            pool_token_user_ata: accounts.pool_token_user_ata,
            pool_token_program: accounts.pool_token_program,
            token_a_token_program: accounts.token_a_token_program,
            token_b_token_program: accounts.token_b_token_program,
            event_authority: accounts.event_authority,
            program: accounts.program,
            __args: args,
        }
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], &[])
    }
    #[inline(always)]
    pub fn invoke_with_remaining_accounts(
        &self,
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
    }
    #[inline(always)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed_with_remaining_accounts(
        &self,
        signers_seeds: &[&[&[u8]]],
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        let mut accounts = Vec::with_capacity(17 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.admin.key,
            true,
        ));
        accounts.push(solana_instruction::AccountMeta::new(*self.pool.key, false));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.swap_curve.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.pool_authority.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.token_a_mint.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.token_b_mint.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.token_a_vault.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.token_b_vault.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.pool_token_mint.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.token_a_user_ata.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.token_b_user_ata.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.pool_token_user_ata.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.pool_token_program.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.token_a_token_program.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.token_b_token_program.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.event_authority.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.program.key,
            false,
        ));
        remaining_accounts.iter().for_each(|remaining_account| {
            accounts.push(solana_instruction::AccountMeta {
                pubkey: *remaining_account.0.key,
                is_signer: remaining_account.1,
                is_writable: remaining_account.2,
            })
        });
        let mut data = DepositInstructionData::new().try_to_vec().unwrap();
        let mut args = self.__args.try_to_vec().unwrap();
        data.append(&mut args);

        let instruction = solana_instruction::Instruction {
            program_id: crate::KDEX_ID,
            accounts,
            data,
        };
        let mut account_infos = Vec::with_capacity(18 + remaining_accounts.len());
        account_infos.push(self.__program.clone());
        account_infos.push(self.admin.clone());
        account_infos.push(self.pool.clone());
        account_infos.push(self.swap_curve.clone());
        account_infos.push(self.pool_authority.clone());
        account_infos.push(self.token_a_mint.clone());
        account_infos.push(self.token_b_mint.clone());
        account_infos.push(self.token_a_vault.clone());
        account_infos.push(self.token_b_vault.clone());
        account_infos.push(self.pool_token_mint.clone());
        account_infos.push(self.token_a_user_ata.clone());
        account_infos.push(self.token_b_user_ata.clone());
        account_infos.push(self.pool_token_user_ata.clone());
        account_infos.push(self.pool_token_program.clone());
        account_infos.push(self.token_a_token_program.clone());
        account_infos.push(self.token_b_token_program.clone());
        account_infos.push(self.event_authority.clone());
        account_infos.push(self.program.clone());
        remaining_accounts
            .iter()
            .for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

        if signers_seeds.is_empty() {
            solana_cpi::invoke(&instruction, &account_infos)
        } else {
            solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
        }
    }
}

/// Instruction builder for `Deposit` via CPI.
///
/// ### Accounts:
///
///   0. `[signer]` admin
///   1. `[writable]` pool
///   2. `[]` swap_curve
///   3. `[]` pool_authority
///   4. `[]` token_a_mint
///   5. `[]` token_b_mint
///   6. `[writable]` token_a_vault
///   7. `[writable]` token_b_vault
///   8. `[writable]` pool_token_mint
///   9. `[writable]` token_a_user_ata
///   10. `[writable]` token_b_user_ata
///   11. `[writable]` pool_token_user_ata
///   12. `[]` pool_token_program
///   13. `[]` token_a_token_program
///   14. `[]` token_b_token_program
///   15. `[]` event_authority
///   16. `[]` program
#[derive(Clone, Debug)]
pub struct DepositCpiBuilder<'a, 'b> {
    instruction: Box<DepositCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> DepositCpiBuilder<'a, 'b> {
    pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
        let instruction = Box::new(DepositCpiBuilderInstruction {
            __program: program,
            admin: None,
            pool: None,
            swap_curve: None,
            pool_authority: None,
            token_a_mint: None,
            token_b_mint: None,
            token_a_vault: None,
            token_b_vault: None,
            pool_token_mint: None,
            token_a_user_ata: None,
            token_b_user_ata: None,
            pool_token_user_ata: None,
            pool_token_program: None,
            token_a_token_program: None,
            token_b_token_program: None,
            event_authority: None,
            program: None,
            pool_token_amount: None,
            maximum_token_a_amount: None,
            maximum_token_b_amount: None,
            __remaining_accounts: Vec::new(),
        });
        Self { instruction }
    }
    #[inline(always)]
    pub fn admin(&mut self, admin: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.admin = Some(admin);
        self
    }
    #[inline(always)]
    pub fn pool(&mut self, pool: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.pool = Some(pool);
        self
    }
    #[inline(always)]
    pub fn swap_curve(
        &mut self,
        swap_curve: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.swap_curve = Some(swap_curve);
        self
    }
    #[inline(always)]
    pub fn pool_authority(
        &mut self,
        pool_authority: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.pool_authority = Some(pool_authority);
        self
    }
    #[inline(always)]
    pub fn token_a_mint(
        &mut self,
        token_a_mint: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.token_a_mint = Some(token_a_mint);
        self
    }
    #[inline(always)]
    pub fn token_b_mint(
        &mut self,
        token_b_mint: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.token_b_mint = Some(token_b_mint);
        self
    }
    #[inline(always)]
    pub fn token_a_vault(
        &mut self,
        token_a_vault: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.token_a_vault = Some(token_a_vault);
        self
    }
    #[inline(always)]
    pub fn token_b_vault(
        &mut self,
        token_b_vault: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.token_b_vault = Some(token_b_vault);
        self
    }
    #[inline(always)]
    pub fn pool_token_mint(
        &mut self,
        pool_token_mint: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.pool_token_mint = Some(pool_token_mint);
        self
    }
    /// Signer's token A token account
    #[inline(always)]
    pub fn token_a_user_ata(
        &mut self,
        token_a_user_ata: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.token_a_user_ata = Some(token_a_user_ata);
        self
    }
    /// Signer's token B token account
    #[inline(always)]
    pub fn token_b_user_ata(
        &mut self,
        token_b_user_ata: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.token_b_user_ata = Some(token_b_user_ata);
        self
    }
    /// Signer's pool token account
    #[inline(always)]
    pub fn pool_token_user_ata(
        &mut self,
        pool_token_user_ata: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.pool_token_user_ata = Some(pool_token_user_ata);
        self
    }
    /// Token program for the pool token mint
    #[inline(always)]
    pub fn pool_token_program(
        &mut self,
        pool_token_program: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.pool_token_program = Some(pool_token_program);
        self
    }
    /// Token program for the source mint
    #[inline(always)]
    pub fn token_a_token_program(
        &mut self,
        token_a_token_program: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.token_a_token_program = Some(token_a_token_program);
        self
    }
    /// Token program for the destination mint
    #[inline(always)]
    pub fn token_b_token_program(
        &mut self,
        token_b_token_program: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.token_b_token_program = Some(token_b_token_program);
        self
    }
    #[inline(always)]
    pub fn event_authority(
        &mut self,
        event_authority: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.event_authority = Some(event_authority);
        self
    }
    #[inline(always)]
    pub fn program(&mut self, program: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.program = Some(program);
        self
    }
    #[inline(always)]
    pub fn pool_token_amount(&mut self, pool_token_amount: u64) -> &mut Self {
        self.instruction.pool_token_amount = Some(pool_token_amount);
        self
    }
    #[inline(always)]
    pub fn maximum_token_a_amount(&mut self, maximum_token_a_amount: u64) -> &mut Self {
        self.instruction.maximum_token_a_amount = Some(maximum_token_a_amount);
        self
    }
    #[inline(always)]
    pub fn maximum_token_b_amount(&mut self, maximum_token_b_amount: u64) -> &mut Self {
        self.instruction.maximum_token_b_amount = Some(maximum_token_b_amount);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(
        &mut self,
        account: &'b solana_account_info::AccountInfo<'a>,
        is_writable: bool,
        is_signer: bool,
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .push((account, is_writable, is_signer));
        self
    }
    /// Add additional accounts to the instruction.
    ///
    /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
    /// and a `bool` indicating whether the account is a signer or not.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .extend_from_slice(accounts);
        self
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed(&[])
    }
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        let args = DepositInstructionArgs {
            pool_token_amount: self
                .instruction
                .pool_token_amount
                .clone()
                .expect("pool_token_amount is not set"),
            maximum_token_a_amount: self
                .instruction
                .maximum_token_a_amount
                .clone()
                .expect("maximum_token_a_amount is not set"),
            maximum_token_b_amount: self
                .instruction
                .maximum_token_b_amount
                .clone()
                .expect("maximum_token_b_amount is not set"),
        };
        let instruction = DepositCpi {
            __program: self.instruction.__program,

            admin: self.instruction.admin.expect("admin is not set"),

            pool: self.instruction.pool.expect("pool is not set"),

            swap_curve: self.instruction.swap_curve.expect("swap_curve is not set"),

            pool_authority: self
                .instruction
                .pool_authority
                .expect("pool_authority is not set"),

            token_a_mint: self
                .instruction
                .token_a_mint
                .expect("token_a_mint is not set"),

            token_b_mint: self
                .instruction
                .token_b_mint
                .expect("token_b_mint is not set"),

            token_a_vault: self
                .instruction
                .token_a_vault
                .expect("token_a_vault is not set"),

            token_b_vault: self
                .instruction
                .token_b_vault
                .expect("token_b_vault is not set"),

            pool_token_mint: self
                .instruction
                .pool_token_mint
                .expect("pool_token_mint is not set"),

            token_a_user_ata: self
                .instruction
                .token_a_user_ata
                .expect("token_a_user_ata is not set"),

            token_b_user_ata: self
                .instruction
                .token_b_user_ata
                .expect("token_b_user_ata is not set"),

            pool_token_user_ata: self
                .instruction
                .pool_token_user_ata
                .expect("pool_token_user_ata is not set"),

            pool_token_program: self
                .instruction
                .pool_token_program
                .expect("pool_token_program is not set"),

            token_a_token_program: self
                .instruction
                .token_a_token_program
                .expect("token_a_token_program is not set"),

            token_b_token_program: self
                .instruction
                .token_b_token_program
                .expect("token_b_token_program is not set"),

            event_authority: self
                .instruction
                .event_authority
                .expect("event_authority is not set"),

            program: self.instruction.program.expect("program is not set"),
            __args: args,
        };
        instruction.invoke_signed_with_remaining_accounts(
            signers_seeds,
            &self.instruction.__remaining_accounts,
        )
    }
}

#[derive(Clone, Debug)]
struct DepositCpiBuilderInstruction<'a, 'b> {
    __program: &'b solana_account_info::AccountInfo<'a>,
    admin: Option<&'b solana_account_info::AccountInfo<'a>>,
    pool: Option<&'b solana_account_info::AccountInfo<'a>>,
    swap_curve: Option<&'b solana_account_info::AccountInfo<'a>>,
    pool_authority: Option<&'b solana_account_info::AccountInfo<'a>>,
    token_a_mint: Option<&'b solana_account_info::AccountInfo<'a>>,
    token_b_mint: Option<&'b solana_account_info::AccountInfo<'a>>,
    token_a_vault: Option<&'b solana_account_info::AccountInfo<'a>>,
    token_b_vault: Option<&'b solana_account_info::AccountInfo<'a>>,
    pool_token_mint: Option<&'b solana_account_info::AccountInfo<'a>>,
    token_a_user_ata: Option<&'b solana_account_info::AccountInfo<'a>>,
    token_b_user_ata: Option<&'b solana_account_info::AccountInfo<'a>>,
    pool_token_user_ata: Option<&'b solana_account_info::AccountInfo<'a>>,
    pool_token_program: Option<&'b solana_account_info::AccountInfo<'a>>,
    token_a_token_program: Option<&'b solana_account_info::AccountInfo<'a>>,
    token_b_token_program: Option<&'b solana_account_info::AccountInfo<'a>>,
    event_authority: Option<&'b solana_account_info::AccountInfo<'a>>,
    program: Option<&'b solana_account_info::AccountInfo<'a>>,
    pool_token_amount: Option<u64>,
    maximum_token_a_amount: Option<u64>,
    maximum_token_b_amount: Option<u64>,
    /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
    __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}
