//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use crate::generated::types::CurveUserParameters;
use crate::generated::types::Fees;
use borsh::BorshDeserialize;
use borsh::BorshSerialize;

pub const INITIALIZE_POOL_DISCRIMINATOR: [u8; 8] = [95, 180, 10, 172, 84, 174, 232, 40];

/// Accounts.
#[derive(Debug)]
pub struct InitializePool {
    pub admin: solana_pubkey::Pubkey,

    pub pool: solana_pubkey::Pubkey,

    pub swap_curve: solana_pubkey::Pubkey,

    pub pool_authority: solana_pubkey::Pubkey,
    /// Token A mint
    pub token_a_mint: solana_pubkey::Pubkey,
    /// Token B mint
    pub token_b_mint: solana_pubkey::Pubkey,

    pub token_a_vault: solana_pubkey::Pubkey,

    pub token_b_vault: solana_pubkey::Pubkey,

    pub pool_token_mint: solana_pubkey::Pubkey,
    /// Token account to collect trading token a fees into - designated to the pool admin authority
    pub token_a_fees_vault: solana_pubkey::Pubkey,
    /// Token account to collect trading token b fees into - designated to the pool admin authority
    pub token_b_fees_vault: solana_pubkey::Pubkey,
    /// Admin authority's token A account to deposit initial liquidity from
    pub admin_token_a_ata: solana_pubkey::Pubkey,
    /// Admin authority's token B account to deposit initial liquidity from
    pub admin_token_b_ata: solana_pubkey::Pubkey,
    /// Admin authority's pool token account to deposit the initially minted pool tokens into
    pub admin_pool_token_ata: solana_pubkey::Pubkey,

    pub system_program: solana_pubkey::Pubkey,

    pub rent: solana_pubkey::Pubkey,
    /// The token program for the pool token mint
    pub pool_token_program: solana_pubkey::Pubkey,
    /// The token program for the token A mint
    pub token_a_token_program: solana_pubkey::Pubkey,
    /// The token program for the token B mint
    pub token_b_token_program: solana_pubkey::Pubkey,

    pub event_authority: solana_pubkey::Pubkey,

    pub program: solana_pubkey::Pubkey,
}

impl InitializePool {
    pub fn instruction(
        &self,
        args: InitializePoolInstructionArgs,
    ) -> solana_instruction::Instruction {
        self.instruction_with_remaining_accounts(args, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::vec_init_then_push)]
    pub fn instruction_with_remaining_accounts(
        &self,
        args: InitializePoolInstructionArgs,
        remaining_accounts: &[solana_instruction::AccountMeta],
    ) -> solana_instruction::Instruction {
        let mut accounts = Vec::with_capacity(21 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new(self.admin, true));
        accounts.push(solana_instruction::AccountMeta::new(self.pool, false));
        accounts.push(solana_instruction::AccountMeta::new(self.swap_curve, false));
        accounts.push(solana_instruction::AccountMeta::new(
            self.pool_authority,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.token_a_mint,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.token_b_mint,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.token_a_vault,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.token_b_vault,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.pool_token_mint,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.token_a_fees_vault,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.token_b_fees_vault,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.admin_token_a_ata,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.admin_token_b_ata,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.admin_pool_token_ata,
            true,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.system_program,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.rent, false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.pool_token_program,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.token_a_token_program,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.token_b_token_program,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.event_authority,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.program,
            false,
        ));
        accounts.extend_from_slice(remaining_accounts);
        let mut data = InitializePoolInstructionData::new().try_to_vec().unwrap();
        let mut args = args.try_to_vec().unwrap();
        data.append(&mut args);

        solana_instruction::Instruction {
            program_id: crate::KDEX_ID,
            accounts,
            data,
        }
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct InitializePoolInstructionData {
    discriminator: [u8; 8],
}

impl InitializePoolInstructionData {
    pub fn new() -> Self {
        Self {
            discriminator: [95, 180, 10, 172, 84, 174, 232, 40],
        }
    }

    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
        borsh::to_vec(self)
    }
}

impl Default for InitializePoolInstructionData {
    fn default() -> Self {
        Self::new()
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct InitializePoolInstructionArgs {
    pub curve_parameters: CurveUserParameters,
    pub fees: Fees,
    pub initial_supply_a: u64,
    pub initial_supply_b: u64,
}

impl InitializePoolInstructionArgs {
    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
        borsh::to_vec(self)
    }
}

/// Instruction builder for `InitializePool`.
///
/// ### Accounts:
///
///   0. `[writable, signer]` admin
///   1. `[writable]` pool
///   2. `[writable]` swap_curve
///   3. `[writable]` pool_authority
///   4. `[]` token_a_mint
///   5. `[]` token_b_mint
///   6. `[writable]` token_a_vault
///   7. `[writable]` token_b_vault
///   8. `[writable]` pool_token_mint
///   9. `[writable]` token_a_fees_vault
///   10. `[writable]` token_b_fees_vault
///   11. `[writable]` admin_token_a_ata
///   12. `[writable]` admin_token_b_ata
///   13. `[writable, signer]` admin_pool_token_ata
///   14. `[optional]` system_program (default to `11111111111111111111111111111111`)
///   15. `[optional]` rent (default to `SysvarRent111111111111111111111111111111111`)
///   16. `[]` pool_token_program
///   17. `[]` token_a_token_program
///   18. `[]` token_b_token_program
///   19. `[]` event_authority
///   20. `[]` program
#[derive(Clone, Debug, Default)]
pub struct InitializePoolBuilder {
    admin: Option<solana_pubkey::Pubkey>,
    pool: Option<solana_pubkey::Pubkey>,
    swap_curve: Option<solana_pubkey::Pubkey>,
    pool_authority: Option<solana_pubkey::Pubkey>,
    token_a_mint: Option<solana_pubkey::Pubkey>,
    token_b_mint: Option<solana_pubkey::Pubkey>,
    token_a_vault: Option<solana_pubkey::Pubkey>,
    token_b_vault: Option<solana_pubkey::Pubkey>,
    pool_token_mint: Option<solana_pubkey::Pubkey>,
    token_a_fees_vault: Option<solana_pubkey::Pubkey>,
    token_b_fees_vault: Option<solana_pubkey::Pubkey>,
    admin_token_a_ata: Option<solana_pubkey::Pubkey>,
    admin_token_b_ata: Option<solana_pubkey::Pubkey>,
    admin_pool_token_ata: Option<solana_pubkey::Pubkey>,
    system_program: Option<solana_pubkey::Pubkey>,
    rent: Option<solana_pubkey::Pubkey>,
    pool_token_program: Option<solana_pubkey::Pubkey>,
    token_a_token_program: Option<solana_pubkey::Pubkey>,
    token_b_token_program: Option<solana_pubkey::Pubkey>,
    event_authority: Option<solana_pubkey::Pubkey>,
    program: Option<solana_pubkey::Pubkey>,
    curve_parameters: Option<CurveUserParameters>,
    fees: Option<Fees>,
    initial_supply_a: Option<u64>,
    initial_supply_b: Option<u64>,
    __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl InitializePoolBuilder {
    pub fn new() -> Self {
        Self::default()
    }
    #[inline(always)]
    pub fn admin(&mut self, admin: solana_pubkey::Pubkey) -> &mut Self {
        self.admin = Some(admin);
        self
    }
    #[inline(always)]
    pub fn pool(&mut self, pool: solana_pubkey::Pubkey) -> &mut Self {
        self.pool = Some(pool);
        self
    }
    #[inline(always)]
    pub fn swap_curve(&mut self, swap_curve: solana_pubkey::Pubkey) -> &mut Self {
        self.swap_curve = Some(swap_curve);
        self
    }
    #[inline(always)]
    pub fn pool_authority(&mut self, pool_authority: solana_pubkey::Pubkey) -> &mut Self {
        self.pool_authority = Some(pool_authority);
        self
    }
    /// Token A mint
    #[inline(always)]
    pub fn token_a_mint(&mut self, token_a_mint: solana_pubkey::Pubkey) -> &mut Self {
        self.token_a_mint = Some(token_a_mint);
        self
    }
    /// Token B mint
    #[inline(always)]
    pub fn token_b_mint(&mut self, token_b_mint: solana_pubkey::Pubkey) -> &mut Self {
        self.token_b_mint = Some(token_b_mint);
        self
    }
    #[inline(always)]
    pub fn token_a_vault(&mut self, token_a_vault: solana_pubkey::Pubkey) -> &mut Self {
        self.token_a_vault = Some(token_a_vault);
        self
    }
    #[inline(always)]
    pub fn token_b_vault(&mut self, token_b_vault: solana_pubkey::Pubkey) -> &mut Self {
        self.token_b_vault = Some(token_b_vault);
        self
    }
    #[inline(always)]
    pub fn pool_token_mint(&mut self, pool_token_mint: solana_pubkey::Pubkey) -> &mut Self {
        self.pool_token_mint = Some(pool_token_mint);
        self
    }
    /// Token account to collect trading token a fees into - designated to the pool admin authority
    #[inline(always)]
    pub fn token_a_fees_vault(&mut self, token_a_fees_vault: solana_pubkey::Pubkey) -> &mut Self {
        self.token_a_fees_vault = Some(token_a_fees_vault);
        self
    }
    /// Token account to collect trading token b fees into - designated to the pool admin authority
    #[inline(always)]
    pub fn token_b_fees_vault(&mut self, token_b_fees_vault: solana_pubkey::Pubkey) -> &mut Self {
        self.token_b_fees_vault = Some(token_b_fees_vault);
        self
    }
    /// Admin authority's token A account to deposit initial liquidity from
    #[inline(always)]
    pub fn admin_token_a_ata(&mut self, admin_token_a_ata: solana_pubkey::Pubkey) -> &mut Self {
        self.admin_token_a_ata = Some(admin_token_a_ata);
        self
    }
    /// Admin authority's token B account to deposit initial liquidity from
    #[inline(always)]
    pub fn admin_token_b_ata(&mut self, admin_token_b_ata: solana_pubkey::Pubkey) -> &mut Self {
        self.admin_token_b_ata = Some(admin_token_b_ata);
        self
    }
    /// Admin authority's pool token account to deposit the initially minted pool tokens into
    #[inline(always)]
    pub fn admin_pool_token_ata(
        &mut self,
        admin_pool_token_ata: solana_pubkey::Pubkey,
    ) -> &mut Self {
        self.admin_pool_token_ata = Some(admin_pool_token_ata);
        self
    }
    /// `[optional account, default to '11111111111111111111111111111111']`
    #[inline(always)]
    pub fn system_program(&mut self, system_program: solana_pubkey::Pubkey) -> &mut Self {
        self.system_program = Some(system_program);
        self
    }
    /// `[optional account, default to 'SysvarRent111111111111111111111111111111111']`
    #[inline(always)]
    pub fn rent(&mut self, rent: solana_pubkey::Pubkey) -> &mut Self {
        self.rent = Some(rent);
        self
    }
    /// The token program for the pool token mint
    #[inline(always)]
    pub fn pool_token_program(&mut self, pool_token_program: solana_pubkey::Pubkey) -> &mut Self {
        self.pool_token_program = Some(pool_token_program);
        self
    }
    /// The token program for the token A mint
    #[inline(always)]
    pub fn token_a_token_program(
        &mut self,
        token_a_token_program: solana_pubkey::Pubkey,
    ) -> &mut Self {
        self.token_a_token_program = Some(token_a_token_program);
        self
    }
    /// The token program for the token B mint
    #[inline(always)]
    pub fn token_b_token_program(
        &mut self,
        token_b_token_program: solana_pubkey::Pubkey,
    ) -> &mut Self {
        self.token_b_token_program = Some(token_b_token_program);
        self
    }
    #[inline(always)]
    pub fn event_authority(&mut self, event_authority: solana_pubkey::Pubkey) -> &mut Self {
        self.event_authority = Some(event_authority);
        self
    }
    #[inline(always)]
    pub fn program(&mut self, program: solana_pubkey::Pubkey) -> &mut Self {
        self.program = Some(program);
        self
    }
    #[inline(always)]
    pub fn curve_parameters(&mut self, curve_parameters: CurveUserParameters) -> &mut Self {
        self.curve_parameters = Some(curve_parameters);
        self
    }
    #[inline(always)]
    pub fn fees(&mut self, fees: Fees) -> &mut Self {
        self.fees = Some(fees);
        self
    }
    #[inline(always)]
    pub fn initial_supply_a(&mut self, initial_supply_a: u64) -> &mut Self {
        self.initial_supply_a = Some(initial_supply_a);
        self
    }
    #[inline(always)]
    pub fn initial_supply_b(&mut self, initial_supply_b: u64) -> &mut Self {
        self.initial_supply_b = Some(initial_supply_b);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
        self.__remaining_accounts.push(account);
        self
    }
    /// Add additional accounts to the instruction.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[solana_instruction::AccountMeta],
    ) -> &mut Self {
        self.__remaining_accounts.extend_from_slice(accounts);
        self
    }
    #[allow(clippy::clone_on_copy)]
    pub fn instruction(&self) -> solana_instruction::Instruction {
        let accounts = InitializePool {
            admin: self.admin.expect("admin is not set"),
            pool: self.pool.expect("pool is not set"),
            swap_curve: self.swap_curve.expect("swap_curve is not set"),
            pool_authority: self.pool_authority.expect("pool_authority is not set"),
            token_a_mint: self.token_a_mint.expect("token_a_mint is not set"),
            token_b_mint: self.token_b_mint.expect("token_b_mint is not set"),
            token_a_vault: self.token_a_vault.expect("token_a_vault is not set"),
            token_b_vault: self.token_b_vault.expect("token_b_vault is not set"),
            pool_token_mint: self.pool_token_mint.expect("pool_token_mint is not set"),
            token_a_fees_vault: self
                .token_a_fees_vault
                .expect("token_a_fees_vault is not set"),
            token_b_fees_vault: self
                .token_b_fees_vault
                .expect("token_b_fees_vault is not set"),
            admin_token_a_ata: self
                .admin_token_a_ata
                .expect("admin_token_a_ata is not set"),
            admin_token_b_ata: self
                .admin_token_b_ata
                .expect("admin_token_b_ata is not set"),
            admin_pool_token_ata: self
                .admin_pool_token_ata
                .expect("admin_pool_token_ata is not set"),
            system_program: self
                .system_program
                .unwrap_or(solana_pubkey::pubkey!("11111111111111111111111111111111")),
            rent: self.rent.unwrap_or(solana_pubkey::pubkey!(
                "SysvarRent111111111111111111111111111111111"
            )),
            pool_token_program: self
                .pool_token_program
                .expect("pool_token_program is not set"),
            token_a_token_program: self
                .token_a_token_program
                .expect("token_a_token_program is not set"),
            token_b_token_program: self
                .token_b_token_program
                .expect("token_b_token_program is not set"),
            event_authority: self.event_authority.expect("event_authority is not set"),
            program: self.program.expect("program is not set"),
        };
        let args = InitializePoolInstructionArgs {
            curve_parameters: self
                .curve_parameters
                .clone()
                .expect("curve_parameters is not set"),
            fees: self.fees.clone().expect("fees is not set"),
            initial_supply_a: self
                .initial_supply_a
                .clone()
                .expect("initial_supply_a is not set"),
            initial_supply_b: self
                .initial_supply_b
                .clone()
                .expect("initial_supply_b is not set"),
        };

        accounts.instruction_with_remaining_accounts(args, &self.__remaining_accounts)
    }
}

/// `initialize_pool` CPI accounts.
pub struct InitializePoolCpiAccounts<'a, 'b> {
    pub admin: &'b solana_account_info::AccountInfo<'a>,

    pub pool: &'b solana_account_info::AccountInfo<'a>,

    pub swap_curve: &'b solana_account_info::AccountInfo<'a>,

    pub pool_authority: &'b solana_account_info::AccountInfo<'a>,
    /// Token A mint
    pub token_a_mint: &'b solana_account_info::AccountInfo<'a>,
    /// Token B mint
    pub token_b_mint: &'b solana_account_info::AccountInfo<'a>,

    pub token_a_vault: &'b solana_account_info::AccountInfo<'a>,

    pub token_b_vault: &'b solana_account_info::AccountInfo<'a>,

    pub pool_token_mint: &'b solana_account_info::AccountInfo<'a>,
    /// Token account to collect trading token a fees into - designated to the pool admin authority
    pub token_a_fees_vault: &'b solana_account_info::AccountInfo<'a>,
    /// Token account to collect trading token b fees into - designated to the pool admin authority
    pub token_b_fees_vault: &'b solana_account_info::AccountInfo<'a>,
    /// Admin authority's token A account to deposit initial liquidity from
    pub admin_token_a_ata: &'b solana_account_info::AccountInfo<'a>,
    /// Admin authority's token B account to deposit initial liquidity from
    pub admin_token_b_ata: &'b solana_account_info::AccountInfo<'a>,
    /// Admin authority's pool token account to deposit the initially minted pool tokens into
    pub admin_pool_token_ata: &'b solana_account_info::AccountInfo<'a>,

    pub system_program: &'b solana_account_info::AccountInfo<'a>,

    pub rent: &'b solana_account_info::AccountInfo<'a>,
    /// The token program for the pool token mint
    pub pool_token_program: &'b solana_account_info::AccountInfo<'a>,
    /// The token program for the token A mint
    pub token_a_token_program: &'b solana_account_info::AccountInfo<'a>,
    /// The token program for the token B mint
    pub token_b_token_program: &'b solana_account_info::AccountInfo<'a>,

    pub event_authority: &'b solana_account_info::AccountInfo<'a>,

    pub program: &'b solana_account_info::AccountInfo<'a>,
}

/// `initialize_pool` CPI instruction.
pub struct InitializePoolCpi<'a, 'b> {
    /// The program to invoke.
    pub __program: &'b solana_account_info::AccountInfo<'a>,

    pub admin: &'b solana_account_info::AccountInfo<'a>,

    pub pool: &'b solana_account_info::AccountInfo<'a>,

    pub swap_curve: &'b solana_account_info::AccountInfo<'a>,

    pub pool_authority: &'b solana_account_info::AccountInfo<'a>,
    /// Token A mint
    pub token_a_mint: &'b solana_account_info::AccountInfo<'a>,
    /// Token B mint
    pub token_b_mint: &'b solana_account_info::AccountInfo<'a>,

    pub token_a_vault: &'b solana_account_info::AccountInfo<'a>,

    pub token_b_vault: &'b solana_account_info::AccountInfo<'a>,

    pub pool_token_mint: &'b solana_account_info::AccountInfo<'a>,
    /// Token account to collect trading token a fees into - designated to the pool admin authority
    pub token_a_fees_vault: &'b solana_account_info::AccountInfo<'a>,
    /// Token account to collect trading token b fees into - designated to the pool admin authority
    pub token_b_fees_vault: &'b solana_account_info::AccountInfo<'a>,
    /// Admin authority's token A account to deposit initial liquidity from
    pub admin_token_a_ata: &'b solana_account_info::AccountInfo<'a>,
    /// Admin authority's token B account to deposit initial liquidity from
    pub admin_token_b_ata: &'b solana_account_info::AccountInfo<'a>,
    /// Admin authority's pool token account to deposit the initially minted pool tokens into
    pub admin_pool_token_ata: &'b solana_account_info::AccountInfo<'a>,

    pub system_program: &'b solana_account_info::AccountInfo<'a>,

    pub rent: &'b solana_account_info::AccountInfo<'a>,
    /// The token program for the pool token mint
    pub pool_token_program: &'b solana_account_info::AccountInfo<'a>,
    /// The token program for the token A mint
    pub token_a_token_program: &'b solana_account_info::AccountInfo<'a>,
    /// The token program for the token B mint
    pub token_b_token_program: &'b solana_account_info::AccountInfo<'a>,

    pub event_authority: &'b solana_account_info::AccountInfo<'a>,

    pub program: &'b solana_account_info::AccountInfo<'a>,
    /// The arguments for the instruction.
    pub __args: InitializePoolInstructionArgs,
}

impl<'a, 'b> InitializePoolCpi<'a, 'b> {
    pub fn new(
        program: &'b solana_account_info::AccountInfo<'a>,
        accounts: InitializePoolCpiAccounts<'a, 'b>,
        args: InitializePoolInstructionArgs,
    ) -> Self {
        Self {
            __program: program,
            admin: accounts.admin,
            pool: accounts.pool,
            swap_curve: accounts.swap_curve,
            pool_authority: accounts.pool_authority,
            token_a_mint: accounts.token_a_mint,
            token_b_mint: accounts.token_b_mint,
            token_a_vault: accounts.token_a_vault,
            token_b_vault: accounts.token_b_vault,
            pool_token_mint: accounts.pool_token_mint,
            token_a_fees_vault: accounts.token_a_fees_vault,
            token_b_fees_vault: accounts.token_b_fees_vault,
            admin_token_a_ata: accounts.admin_token_a_ata,
            admin_token_b_ata: accounts.admin_token_b_ata,
            admin_pool_token_ata: accounts.admin_pool_token_ata,
            system_program: accounts.system_program,
            rent: accounts.rent,
            pool_token_program: accounts.pool_token_program,
            token_a_token_program: accounts.token_a_token_program,
            token_b_token_program: accounts.token_b_token_program,
            event_authority: accounts.event_authority,
            program: accounts.program,
            __args: args,
        }
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], &[])
    }
    #[inline(always)]
    pub fn invoke_with_remaining_accounts(
        &self,
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
    }
    #[inline(always)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed_with_remaining_accounts(
        &self,
        signers_seeds: &[&[&[u8]]],
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        let mut accounts = Vec::with_capacity(21 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new(*self.admin.key, true));
        accounts.push(solana_instruction::AccountMeta::new(*self.pool.key, false));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.swap_curve.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.pool_authority.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.token_a_mint.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.token_b_mint.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.token_a_vault.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.token_b_vault.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.pool_token_mint.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.token_a_fees_vault.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.token_b_fees_vault.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.admin_token_a_ata.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.admin_token_b_ata.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.admin_pool_token_ata.key,
            true,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.system_program.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.rent.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.pool_token_program.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.token_a_token_program.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.token_b_token_program.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.event_authority.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.program.key,
            false,
        ));
        remaining_accounts.iter().for_each(|remaining_account| {
            accounts.push(solana_instruction::AccountMeta {
                pubkey: *remaining_account.0.key,
                is_signer: remaining_account.1,
                is_writable: remaining_account.2,
            })
        });
        let mut data = InitializePoolInstructionData::new().try_to_vec().unwrap();
        let mut args = self.__args.try_to_vec().unwrap();
        data.append(&mut args);

        let instruction = solana_instruction::Instruction {
            program_id: crate::KDEX_ID,
            accounts,
            data,
        };
        let mut account_infos = Vec::with_capacity(22 + remaining_accounts.len());
        account_infos.push(self.__program.clone());
        account_infos.push(self.admin.clone());
        account_infos.push(self.pool.clone());
        account_infos.push(self.swap_curve.clone());
        account_infos.push(self.pool_authority.clone());
        account_infos.push(self.token_a_mint.clone());
        account_infos.push(self.token_b_mint.clone());
        account_infos.push(self.token_a_vault.clone());
        account_infos.push(self.token_b_vault.clone());
        account_infos.push(self.pool_token_mint.clone());
        account_infos.push(self.token_a_fees_vault.clone());
        account_infos.push(self.token_b_fees_vault.clone());
        account_infos.push(self.admin_token_a_ata.clone());
        account_infos.push(self.admin_token_b_ata.clone());
        account_infos.push(self.admin_pool_token_ata.clone());
        account_infos.push(self.system_program.clone());
        account_infos.push(self.rent.clone());
        account_infos.push(self.pool_token_program.clone());
        account_infos.push(self.token_a_token_program.clone());
        account_infos.push(self.token_b_token_program.clone());
        account_infos.push(self.event_authority.clone());
        account_infos.push(self.program.clone());
        remaining_accounts
            .iter()
            .for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

        if signers_seeds.is_empty() {
            solana_cpi::invoke(&instruction, &account_infos)
        } else {
            solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
        }
    }
}

/// Instruction builder for `InitializePool` via CPI.
///
/// ### Accounts:
///
///   0. `[writable, signer]` admin
///   1. `[writable]` pool
///   2. `[writable]` swap_curve
///   3. `[writable]` pool_authority
///   4. `[]` token_a_mint
///   5. `[]` token_b_mint
///   6. `[writable]` token_a_vault
///   7. `[writable]` token_b_vault
///   8. `[writable]` pool_token_mint
///   9. `[writable]` token_a_fees_vault
///   10. `[writable]` token_b_fees_vault
///   11. `[writable]` admin_token_a_ata
///   12. `[writable]` admin_token_b_ata
///   13. `[writable, signer]` admin_pool_token_ata
///   14. `[]` system_program
///   15. `[]` rent
///   16. `[]` pool_token_program
///   17. `[]` token_a_token_program
///   18. `[]` token_b_token_program
///   19. `[]` event_authority
///   20. `[]` program
#[derive(Clone, Debug)]
pub struct InitializePoolCpiBuilder<'a, 'b> {
    instruction: Box<InitializePoolCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> InitializePoolCpiBuilder<'a, 'b> {
    pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
        let instruction = Box::new(InitializePoolCpiBuilderInstruction {
            __program: program,
            admin: None,
            pool: None,
            swap_curve: None,
            pool_authority: None,
            token_a_mint: None,
            token_b_mint: None,
            token_a_vault: None,
            token_b_vault: None,
            pool_token_mint: None,
            token_a_fees_vault: None,
            token_b_fees_vault: None,
            admin_token_a_ata: None,
            admin_token_b_ata: None,
            admin_pool_token_ata: None,
            system_program: None,
            rent: None,
            pool_token_program: None,
            token_a_token_program: None,
            token_b_token_program: None,
            event_authority: None,
            program: None,
            curve_parameters: None,
            fees: None,
            initial_supply_a: None,
            initial_supply_b: None,
            __remaining_accounts: Vec::new(),
        });
        Self { instruction }
    }
    #[inline(always)]
    pub fn admin(&mut self, admin: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.admin = Some(admin);
        self
    }
    #[inline(always)]
    pub fn pool(&mut self, pool: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.pool = Some(pool);
        self
    }
    #[inline(always)]
    pub fn swap_curve(
        &mut self,
        swap_curve: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.swap_curve = Some(swap_curve);
        self
    }
    #[inline(always)]
    pub fn pool_authority(
        &mut self,
        pool_authority: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.pool_authority = Some(pool_authority);
        self
    }
    /// Token A mint
    #[inline(always)]
    pub fn token_a_mint(
        &mut self,
        token_a_mint: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.token_a_mint = Some(token_a_mint);
        self
    }
    /// Token B mint
    #[inline(always)]
    pub fn token_b_mint(
        &mut self,
        token_b_mint: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.token_b_mint = Some(token_b_mint);
        self
    }
    #[inline(always)]
    pub fn token_a_vault(
        &mut self,
        token_a_vault: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.token_a_vault = Some(token_a_vault);
        self
    }
    #[inline(always)]
    pub fn token_b_vault(
        &mut self,
        token_b_vault: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.token_b_vault = Some(token_b_vault);
        self
    }
    #[inline(always)]
    pub fn pool_token_mint(
        &mut self,
        pool_token_mint: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.pool_token_mint = Some(pool_token_mint);
        self
    }
    /// Token account to collect trading token a fees into - designated to the pool admin authority
    #[inline(always)]
    pub fn token_a_fees_vault(
        &mut self,
        token_a_fees_vault: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.token_a_fees_vault = Some(token_a_fees_vault);
        self
    }
    /// Token account to collect trading token b fees into - designated to the pool admin authority
    #[inline(always)]
    pub fn token_b_fees_vault(
        &mut self,
        token_b_fees_vault: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.token_b_fees_vault = Some(token_b_fees_vault);
        self
    }
    /// Admin authority's token A account to deposit initial liquidity from
    #[inline(always)]
    pub fn admin_token_a_ata(
        &mut self,
        admin_token_a_ata: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.admin_token_a_ata = Some(admin_token_a_ata);
        self
    }
    /// Admin authority's token B account to deposit initial liquidity from
    #[inline(always)]
    pub fn admin_token_b_ata(
        &mut self,
        admin_token_b_ata: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.admin_token_b_ata = Some(admin_token_b_ata);
        self
    }
    /// Admin authority's pool token account to deposit the initially minted pool tokens into
    #[inline(always)]
    pub fn admin_pool_token_ata(
        &mut self,
        admin_pool_token_ata: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.admin_pool_token_ata = Some(admin_pool_token_ata);
        self
    }
    #[inline(always)]
    pub fn system_program(
        &mut self,
        system_program: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.system_program = Some(system_program);
        self
    }
    #[inline(always)]
    pub fn rent(&mut self, rent: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.rent = Some(rent);
        self
    }
    /// The token program for the pool token mint
    #[inline(always)]
    pub fn pool_token_program(
        &mut self,
        pool_token_program: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.pool_token_program = Some(pool_token_program);
        self
    }
    /// The token program for the token A mint
    #[inline(always)]
    pub fn token_a_token_program(
        &mut self,
        token_a_token_program: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.token_a_token_program = Some(token_a_token_program);
        self
    }
    /// The token program for the token B mint
    #[inline(always)]
    pub fn token_b_token_program(
        &mut self,
        token_b_token_program: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.token_b_token_program = Some(token_b_token_program);
        self
    }
    #[inline(always)]
    pub fn event_authority(
        &mut self,
        event_authority: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.event_authority = Some(event_authority);
        self
    }
    #[inline(always)]
    pub fn program(&mut self, program: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.program = Some(program);
        self
    }
    #[inline(always)]
    pub fn curve_parameters(&mut self, curve_parameters: CurveUserParameters) -> &mut Self {
        self.instruction.curve_parameters = Some(curve_parameters);
        self
    }
    #[inline(always)]
    pub fn fees(&mut self, fees: Fees) -> &mut Self {
        self.instruction.fees = Some(fees);
        self
    }
    #[inline(always)]
    pub fn initial_supply_a(&mut self, initial_supply_a: u64) -> &mut Self {
        self.instruction.initial_supply_a = Some(initial_supply_a);
        self
    }
    #[inline(always)]
    pub fn initial_supply_b(&mut self, initial_supply_b: u64) -> &mut Self {
        self.instruction.initial_supply_b = Some(initial_supply_b);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(
        &mut self,
        account: &'b solana_account_info::AccountInfo<'a>,
        is_writable: bool,
        is_signer: bool,
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .push((account, is_writable, is_signer));
        self
    }
    /// Add additional accounts to the instruction.
    ///
    /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
    /// and a `bool` indicating whether the account is a signer or not.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .extend_from_slice(accounts);
        self
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed(&[])
    }
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        let args = InitializePoolInstructionArgs {
            curve_parameters: self
                .instruction
                .curve_parameters
                .clone()
                .expect("curve_parameters is not set"),
            fees: self.instruction.fees.clone().expect("fees is not set"),
            initial_supply_a: self
                .instruction
                .initial_supply_a
                .clone()
                .expect("initial_supply_a is not set"),
            initial_supply_b: self
                .instruction
                .initial_supply_b
                .clone()
                .expect("initial_supply_b is not set"),
        };
        let instruction = InitializePoolCpi {
            __program: self.instruction.__program,

            admin: self.instruction.admin.expect("admin is not set"),

            pool: self.instruction.pool.expect("pool is not set"),

            swap_curve: self.instruction.swap_curve.expect("swap_curve is not set"),

            pool_authority: self
                .instruction
                .pool_authority
                .expect("pool_authority is not set"),

            token_a_mint: self
                .instruction
                .token_a_mint
                .expect("token_a_mint is not set"),

            token_b_mint: self
                .instruction
                .token_b_mint
                .expect("token_b_mint is not set"),

            token_a_vault: self
                .instruction
                .token_a_vault
                .expect("token_a_vault is not set"),

            token_b_vault: self
                .instruction
                .token_b_vault
                .expect("token_b_vault is not set"),

            pool_token_mint: self
                .instruction
                .pool_token_mint
                .expect("pool_token_mint is not set"),

            token_a_fees_vault: self
                .instruction
                .token_a_fees_vault
                .expect("token_a_fees_vault is not set"),

            token_b_fees_vault: self
                .instruction
                .token_b_fees_vault
                .expect("token_b_fees_vault is not set"),

            admin_token_a_ata: self
                .instruction
                .admin_token_a_ata
                .expect("admin_token_a_ata is not set"),

            admin_token_b_ata: self
                .instruction
                .admin_token_b_ata
                .expect("admin_token_b_ata is not set"),

            admin_pool_token_ata: self
                .instruction
                .admin_pool_token_ata
                .expect("admin_pool_token_ata is not set"),

            system_program: self
                .instruction
                .system_program
                .expect("system_program is not set"),

            rent: self.instruction.rent.expect("rent is not set"),

            pool_token_program: self
                .instruction
                .pool_token_program
                .expect("pool_token_program is not set"),

            token_a_token_program: self
                .instruction
                .token_a_token_program
                .expect("token_a_token_program is not set"),

            token_b_token_program: self
                .instruction
                .token_b_token_program
                .expect("token_b_token_program is not set"),

            event_authority: self
                .instruction
                .event_authority
                .expect("event_authority is not set"),

            program: self.instruction.program.expect("program is not set"),
            __args: args,
        };
        instruction.invoke_signed_with_remaining_accounts(
            signers_seeds,
            &self.instruction.__remaining_accounts,
        )
    }
}

#[derive(Clone, Debug)]
struct InitializePoolCpiBuilderInstruction<'a, 'b> {
    __program: &'b solana_account_info::AccountInfo<'a>,
    admin: Option<&'b solana_account_info::AccountInfo<'a>>,
    pool: Option<&'b solana_account_info::AccountInfo<'a>>,
    swap_curve: Option<&'b solana_account_info::AccountInfo<'a>>,
    pool_authority: Option<&'b solana_account_info::AccountInfo<'a>>,
    token_a_mint: Option<&'b solana_account_info::AccountInfo<'a>>,
    token_b_mint: Option<&'b solana_account_info::AccountInfo<'a>>,
    token_a_vault: Option<&'b solana_account_info::AccountInfo<'a>>,
    token_b_vault: Option<&'b solana_account_info::AccountInfo<'a>>,
    pool_token_mint: Option<&'b solana_account_info::AccountInfo<'a>>,
    token_a_fees_vault: Option<&'b solana_account_info::AccountInfo<'a>>,
    token_b_fees_vault: Option<&'b solana_account_info::AccountInfo<'a>>,
    admin_token_a_ata: Option<&'b solana_account_info::AccountInfo<'a>>,
    admin_token_b_ata: Option<&'b solana_account_info::AccountInfo<'a>>,
    admin_pool_token_ata: Option<&'b solana_account_info::AccountInfo<'a>>,
    system_program: Option<&'b solana_account_info::AccountInfo<'a>>,
    rent: Option<&'b solana_account_info::AccountInfo<'a>>,
    pool_token_program: Option<&'b solana_account_info::AccountInfo<'a>>,
    token_a_token_program: Option<&'b solana_account_info::AccountInfo<'a>>,
    token_b_token_program: Option<&'b solana_account_info::AccountInfo<'a>>,
    event_authority: Option<&'b solana_account_info::AccountInfo<'a>>,
    program: Option<&'b solana_account_info::AccountInfo<'a>>,
    curve_parameters: Option<CurveUserParameters>,
    fees: Option<Fees>,
    initial_supply_a: Option<u64>,
    initial_supply_b: Option<u64>,
    /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
    __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}
