//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

pub(crate) mod r#close_pool;
pub(crate) mod r#deposit;
pub(crate) mod r#initialize_pool;
pub(crate) mod r#swap;
pub(crate) mod r#swap2;
pub(crate) mod r#update_pool_config;
pub(crate) mod r#withdraw;
pub(crate) mod r#withdraw_fees;

pub use self::r#close_pool::*;
pub use self::r#deposit::*;
pub use self::r#initialize_pool::*;
pub use self::r#swap::*;
pub use self::r#swap2::*;
pub use self::r#update_pool_config::*;
pub use self::r#withdraw::*;
pub use self::r#withdraw_fees::*;
