//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshDeserialize;
use borsh::BorshSerialize;

pub const SWAP_DISCRIMINATOR: [u8; 8] = [248, 198, 158, 145, 225, 117, 135, 200];

/// Accounts.
#[derive(Debug)]
pub struct Swap {
    pub signer: solana_pubkey::Pubkey,

    pub pool: solana_pubkey::Pubkey,

    pub swap_curve: solana_pubkey::Pubkey,

    pub pool_authority: solana_pubkey::Pubkey,

    pub source_mint: solana_pubkey::Pubkey,

    pub destination_mint: solana_pubkey::Pubkey,

    pub source_vault: solana_pubkey::Pubkey,

    pub destination_vault: solana_pubkey::Pubkey,
    /// Account to collect fees into
    pub source_token_fees_vault: solana_pubkey::Pubkey,
    /// Signer's source token account
    pub source_user_ata: solana_pubkey::Pubkey,
    /// Signer's destination token account
    pub destination_user_ata: solana_pubkey::Pubkey,
    /// Token program for the source mint
    pub source_token_program: solana_pubkey::Pubkey,
    /// Token program for the destination mint
    pub destination_token_program: solana_pubkey::Pubkey,
    /// Optional pool token fees account for front ends - if not present, all fees are sent to the trading fees account
    pub source_token_host_fees_account: Option<solana_pubkey::Pubkey>,
    /// Optional Scope price feed account (required for Oracle based curves)
    pub scope_price_feed: Option<solana_pubkey::Pubkey>,

    pub event_authority: solana_pubkey::Pubkey,

    pub program: solana_pubkey::Pubkey,
}

impl Swap {
    pub fn instruction(&self, args: SwapInstructionArgs) -> solana_instruction::Instruction {
        self.instruction_with_remaining_accounts(args, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::vec_init_then_push)]
    pub fn instruction_with_remaining_accounts(
        &self,
        args: SwapInstructionArgs,
        remaining_accounts: &[solana_instruction::AccountMeta],
    ) -> solana_instruction::Instruction {
        let mut accounts = Vec::with_capacity(17 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new(self.signer, true));
        accounts.push(solana_instruction::AccountMeta::new(self.pool, false));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.swap_curve,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.pool_authority,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.source_mint,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.destination_mint,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.source_vault,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.destination_vault,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.source_token_fees_vault,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.source_user_ata,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.destination_user_ata,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.source_token_program,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.destination_token_program,
            false,
        ));
        if let Some(source_token_host_fees_account) = self.source_token_host_fees_account {
            accounts.push(solana_instruction::AccountMeta::new(
                source_token_host_fees_account,
                false,
            ));
        } else {
            accounts.push(solana_instruction::AccountMeta::new_readonly(
                crate::KDEX_ID,
                false,
            ));
        }
        if let Some(scope_price_feed) = self.scope_price_feed {
            accounts.push(solana_instruction::AccountMeta::new_readonly(
                scope_price_feed,
                false,
            ));
        } else {
            accounts.push(solana_instruction::AccountMeta::new_readonly(
                crate::KDEX_ID,
                false,
            ));
        }
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.event_authority,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.program,
            false,
        ));
        accounts.extend_from_slice(remaining_accounts);
        let mut data = SwapInstructionData::new().try_to_vec().unwrap();
        let mut args = args.try_to_vec().unwrap();
        data.append(&mut args);

        solana_instruction::Instruction {
            program_id: crate::KDEX_ID,
            accounts,
            data,
        }
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct SwapInstructionData {
    discriminator: [u8; 8],
}

impl SwapInstructionData {
    pub fn new() -> Self {
        Self {
            discriminator: [248, 198, 158, 145, 225, 117, 135, 200],
        }
    }

    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
        borsh::to_vec(self)
    }
}

impl Default for SwapInstructionData {
    fn default() -> Self {
        Self::new()
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct SwapInstructionArgs {
    pub amount_in: u64,
    pub minimum_amount_out: u64,
}

impl SwapInstructionArgs {
    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
        borsh::to_vec(self)
    }
}

/// Instruction builder for `Swap`.
///
/// ### Accounts:
///
///   0. `[writable, signer]` signer
///   1. `[writable]` pool
///   2. `[]` swap_curve
///   3. `[]` pool_authority
///   4. `[]` source_mint
///   5. `[]` destination_mint
///   6. `[writable]` source_vault
///   7. `[writable]` destination_vault
///   8. `[writable]` source_token_fees_vault
///   9. `[writable]` source_user_ata
///   10. `[writable]` destination_user_ata
///   11. `[]` source_token_program
///   12. `[]` destination_token_program
///   13. `[writable, optional]` source_token_host_fees_account
///   14. `[optional]` scope_price_feed
///   15. `[]` event_authority
///   16. `[]` program
#[derive(Clone, Debug, Default)]
pub struct SwapBuilder {
    signer: Option<solana_pubkey::Pubkey>,
    pool: Option<solana_pubkey::Pubkey>,
    swap_curve: Option<solana_pubkey::Pubkey>,
    pool_authority: Option<solana_pubkey::Pubkey>,
    source_mint: Option<solana_pubkey::Pubkey>,
    destination_mint: Option<solana_pubkey::Pubkey>,
    source_vault: Option<solana_pubkey::Pubkey>,
    destination_vault: Option<solana_pubkey::Pubkey>,
    source_token_fees_vault: Option<solana_pubkey::Pubkey>,
    source_user_ata: Option<solana_pubkey::Pubkey>,
    destination_user_ata: Option<solana_pubkey::Pubkey>,
    source_token_program: Option<solana_pubkey::Pubkey>,
    destination_token_program: Option<solana_pubkey::Pubkey>,
    source_token_host_fees_account: Option<solana_pubkey::Pubkey>,
    scope_price_feed: Option<solana_pubkey::Pubkey>,
    event_authority: Option<solana_pubkey::Pubkey>,
    program: Option<solana_pubkey::Pubkey>,
    amount_in: Option<u64>,
    minimum_amount_out: Option<u64>,
    __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl SwapBuilder {
    pub fn new() -> Self {
        Self::default()
    }
    #[inline(always)]
    pub fn signer(&mut self, signer: solana_pubkey::Pubkey) -> &mut Self {
        self.signer = Some(signer);
        self
    }
    #[inline(always)]
    pub fn pool(&mut self, pool: solana_pubkey::Pubkey) -> &mut Self {
        self.pool = Some(pool);
        self
    }
    #[inline(always)]
    pub fn swap_curve(&mut self, swap_curve: solana_pubkey::Pubkey) -> &mut Self {
        self.swap_curve = Some(swap_curve);
        self
    }
    #[inline(always)]
    pub fn pool_authority(&mut self, pool_authority: solana_pubkey::Pubkey) -> &mut Self {
        self.pool_authority = Some(pool_authority);
        self
    }
    #[inline(always)]
    pub fn source_mint(&mut self, source_mint: solana_pubkey::Pubkey) -> &mut Self {
        self.source_mint = Some(source_mint);
        self
    }
    #[inline(always)]
    pub fn destination_mint(&mut self, destination_mint: solana_pubkey::Pubkey) -> &mut Self {
        self.destination_mint = Some(destination_mint);
        self
    }
    #[inline(always)]
    pub fn source_vault(&mut self, source_vault: solana_pubkey::Pubkey) -> &mut Self {
        self.source_vault = Some(source_vault);
        self
    }
    #[inline(always)]
    pub fn destination_vault(&mut self, destination_vault: solana_pubkey::Pubkey) -> &mut Self {
        self.destination_vault = Some(destination_vault);
        self
    }
    /// Account to collect fees into
    #[inline(always)]
    pub fn source_token_fees_vault(
        &mut self,
        source_token_fees_vault: solana_pubkey::Pubkey,
    ) -> &mut Self {
        self.source_token_fees_vault = Some(source_token_fees_vault);
        self
    }
    /// Signer's source token account
    #[inline(always)]
    pub fn source_user_ata(&mut self, source_user_ata: solana_pubkey::Pubkey) -> &mut Self {
        self.source_user_ata = Some(source_user_ata);
        self
    }
    /// Signer's destination token account
    #[inline(always)]
    pub fn destination_user_ata(
        &mut self,
        destination_user_ata: solana_pubkey::Pubkey,
    ) -> &mut Self {
        self.destination_user_ata = Some(destination_user_ata);
        self
    }
    /// Token program for the source mint
    #[inline(always)]
    pub fn source_token_program(
        &mut self,
        source_token_program: solana_pubkey::Pubkey,
    ) -> &mut Self {
        self.source_token_program = Some(source_token_program);
        self
    }
    /// Token program for the destination mint
    #[inline(always)]
    pub fn destination_token_program(
        &mut self,
        destination_token_program: solana_pubkey::Pubkey,
    ) -> &mut Self {
        self.destination_token_program = Some(destination_token_program);
        self
    }
    /// `[optional account]`
    /// Optional pool token fees account for front ends - if not present, all fees are sent to the trading fees account
    #[inline(always)]
    pub fn source_token_host_fees_account(
        &mut self,
        source_token_host_fees_account: Option<solana_pubkey::Pubkey>,
    ) -> &mut Self {
        self.source_token_host_fees_account = source_token_host_fees_account;
        self
    }
    /// `[optional account]`
    /// Optional Scope price feed account (required for Oracle based curves)
    #[inline(always)]
    pub fn scope_price_feed(
        &mut self,
        scope_price_feed: Option<solana_pubkey::Pubkey>,
    ) -> &mut Self {
        self.scope_price_feed = scope_price_feed;
        self
    }
    #[inline(always)]
    pub fn event_authority(&mut self, event_authority: solana_pubkey::Pubkey) -> &mut Self {
        self.event_authority = Some(event_authority);
        self
    }
    #[inline(always)]
    pub fn program(&mut self, program: solana_pubkey::Pubkey) -> &mut Self {
        self.program = Some(program);
        self
    }
    #[inline(always)]
    pub fn amount_in(&mut self, amount_in: u64) -> &mut Self {
        self.amount_in = Some(amount_in);
        self
    }
    #[inline(always)]
    pub fn minimum_amount_out(&mut self, minimum_amount_out: u64) -> &mut Self {
        self.minimum_amount_out = Some(minimum_amount_out);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
        self.__remaining_accounts.push(account);
        self
    }
    /// Add additional accounts to the instruction.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[solana_instruction::AccountMeta],
    ) -> &mut Self {
        self.__remaining_accounts.extend_from_slice(accounts);
        self
    }
    #[allow(clippy::clone_on_copy)]
    pub fn instruction(&self) -> solana_instruction::Instruction {
        let accounts = Swap {
            signer: self.signer.expect("signer is not set"),
            pool: self.pool.expect("pool is not set"),
            swap_curve: self.swap_curve.expect("swap_curve is not set"),
            pool_authority: self.pool_authority.expect("pool_authority is not set"),
            source_mint: self.source_mint.expect("source_mint is not set"),
            destination_mint: self.destination_mint.expect("destination_mint is not set"),
            source_vault: self.source_vault.expect("source_vault is not set"),
            destination_vault: self
                .destination_vault
                .expect("destination_vault is not set"),
            source_token_fees_vault: self
                .source_token_fees_vault
                .expect("source_token_fees_vault is not set"),
            source_user_ata: self.source_user_ata.expect("source_user_ata is not set"),
            destination_user_ata: self
                .destination_user_ata
                .expect("destination_user_ata is not set"),
            source_token_program: self
                .source_token_program
                .expect("source_token_program is not set"),
            destination_token_program: self
                .destination_token_program
                .expect("destination_token_program is not set"),
            source_token_host_fees_account: self.source_token_host_fees_account,
            scope_price_feed: self.scope_price_feed,
            event_authority: self.event_authority.expect("event_authority is not set"),
            program: self.program.expect("program is not set"),
        };
        let args = SwapInstructionArgs {
            amount_in: self.amount_in.clone().expect("amount_in is not set"),
            minimum_amount_out: self
                .minimum_amount_out
                .clone()
                .expect("minimum_amount_out is not set"),
        };

        accounts.instruction_with_remaining_accounts(args, &self.__remaining_accounts)
    }
}

/// `swap` CPI accounts.
pub struct SwapCpiAccounts<'a, 'b> {
    pub signer: &'b solana_account_info::AccountInfo<'a>,

    pub pool: &'b solana_account_info::AccountInfo<'a>,

    pub swap_curve: &'b solana_account_info::AccountInfo<'a>,

    pub pool_authority: &'b solana_account_info::AccountInfo<'a>,

    pub source_mint: &'b solana_account_info::AccountInfo<'a>,

    pub destination_mint: &'b solana_account_info::AccountInfo<'a>,

    pub source_vault: &'b solana_account_info::AccountInfo<'a>,

    pub destination_vault: &'b solana_account_info::AccountInfo<'a>,
    /// Account to collect fees into
    pub source_token_fees_vault: &'b solana_account_info::AccountInfo<'a>,
    /// Signer's source token account
    pub source_user_ata: &'b solana_account_info::AccountInfo<'a>,
    /// Signer's destination token account
    pub destination_user_ata: &'b solana_account_info::AccountInfo<'a>,
    /// Token program for the source mint
    pub source_token_program: &'b solana_account_info::AccountInfo<'a>,
    /// Token program for the destination mint
    pub destination_token_program: &'b solana_account_info::AccountInfo<'a>,
    /// Optional pool token fees account for front ends - if not present, all fees are sent to the trading fees account
    pub source_token_host_fees_account: Option<&'b solana_account_info::AccountInfo<'a>>,
    /// Optional Scope price feed account (required for Oracle based curves)
    pub scope_price_feed: Option<&'b solana_account_info::AccountInfo<'a>>,

    pub event_authority: &'b solana_account_info::AccountInfo<'a>,

    pub program: &'b solana_account_info::AccountInfo<'a>,
}

/// `swap` CPI instruction.
pub struct SwapCpi<'a, 'b> {
    /// The program to invoke.
    pub __program: &'b solana_account_info::AccountInfo<'a>,

    pub signer: &'b solana_account_info::AccountInfo<'a>,

    pub pool: &'b solana_account_info::AccountInfo<'a>,

    pub swap_curve: &'b solana_account_info::AccountInfo<'a>,

    pub pool_authority: &'b solana_account_info::AccountInfo<'a>,

    pub source_mint: &'b solana_account_info::AccountInfo<'a>,

    pub destination_mint: &'b solana_account_info::AccountInfo<'a>,

    pub source_vault: &'b solana_account_info::AccountInfo<'a>,

    pub destination_vault: &'b solana_account_info::AccountInfo<'a>,
    /// Account to collect fees into
    pub source_token_fees_vault: &'b solana_account_info::AccountInfo<'a>,
    /// Signer's source token account
    pub source_user_ata: &'b solana_account_info::AccountInfo<'a>,
    /// Signer's destination token account
    pub destination_user_ata: &'b solana_account_info::AccountInfo<'a>,
    /// Token program for the source mint
    pub source_token_program: &'b solana_account_info::AccountInfo<'a>,
    /// Token program for the destination mint
    pub destination_token_program: &'b solana_account_info::AccountInfo<'a>,
    /// Optional pool token fees account for front ends - if not present, all fees are sent to the trading fees account
    pub source_token_host_fees_account: Option<&'b solana_account_info::AccountInfo<'a>>,
    /// Optional Scope price feed account (required for Oracle based curves)
    pub scope_price_feed: Option<&'b solana_account_info::AccountInfo<'a>>,

    pub event_authority: &'b solana_account_info::AccountInfo<'a>,

    pub program: &'b solana_account_info::AccountInfo<'a>,
    /// The arguments for the instruction.
    pub __args: SwapInstructionArgs,
}

impl<'a, 'b> SwapCpi<'a, 'b> {
    pub fn new(
        program: &'b solana_account_info::AccountInfo<'a>,
        accounts: SwapCpiAccounts<'a, 'b>,
        args: SwapInstructionArgs,
    ) -> Self {
        Self {
            __program: program,
            signer: accounts.signer,
            pool: accounts.pool,
            swap_curve: accounts.swap_curve,
            pool_authority: accounts.pool_authority,
            source_mint: accounts.source_mint,
            destination_mint: accounts.destination_mint,
            source_vault: accounts.source_vault,
            destination_vault: accounts.destination_vault,
            source_token_fees_vault: accounts.source_token_fees_vault,
            source_user_ata: accounts.source_user_ata,
            destination_user_ata: accounts.destination_user_ata,
            source_token_program: accounts.source_token_program,
            destination_token_program: accounts.destination_token_program,
            source_token_host_fees_account: accounts.source_token_host_fees_account,
            scope_price_feed: accounts.scope_price_feed,
            event_authority: accounts.event_authority,
            program: accounts.program,
            __args: args,
        }
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], &[])
    }
    #[inline(always)]
    pub fn invoke_with_remaining_accounts(
        &self,
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
    }
    #[inline(always)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed_with_remaining_accounts(
        &self,
        signers_seeds: &[&[&[u8]]],
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        let mut accounts = Vec::with_capacity(17 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new(*self.signer.key, true));
        accounts.push(solana_instruction::AccountMeta::new(*self.pool.key, false));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.swap_curve.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.pool_authority.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.source_mint.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.destination_mint.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.source_vault.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.destination_vault.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.source_token_fees_vault.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.source_user_ata.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.destination_user_ata.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.source_token_program.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.destination_token_program.key,
            false,
        ));
        if let Some(source_token_host_fees_account) = self.source_token_host_fees_account {
            accounts.push(solana_instruction::AccountMeta::new(
                *source_token_host_fees_account.key,
                false,
            ));
        } else {
            accounts.push(solana_instruction::AccountMeta::new_readonly(
                crate::KDEX_ID,
                false,
            ));
        }
        if let Some(scope_price_feed) = self.scope_price_feed {
            accounts.push(solana_instruction::AccountMeta::new_readonly(
                *scope_price_feed.key,
                false,
            ));
        } else {
            accounts.push(solana_instruction::AccountMeta::new_readonly(
                crate::KDEX_ID,
                false,
            ));
        }
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.event_authority.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.program.key,
            false,
        ));
        remaining_accounts.iter().for_each(|remaining_account| {
            accounts.push(solana_instruction::AccountMeta {
                pubkey: *remaining_account.0.key,
                is_signer: remaining_account.1,
                is_writable: remaining_account.2,
            })
        });
        let mut data = SwapInstructionData::new().try_to_vec().unwrap();
        let mut args = self.__args.try_to_vec().unwrap();
        data.append(&mut args);

        let instruction = solana_instruction::Instruction {
            program_id: crate::KDEX_ID,
            accounts,
            data,
        };
        let mut account_infos = Vec::with_capacity(18 + remaining_accounts.len());
        account_infos.push(self.__program.clone());
        account_infos.push(self.signer.clone());
        account_infos.push(self.pool.clone());
        account_infos.push(self.swap_curve.clone());
        account_infos.push(self.pool_authority.clone());
        account_infos.push(self.source_mint.clone());
        account_infos.push(self.destination_mint.clone());
        account_infos.push(self.source_vault.clone());
        account_infos.push(self.destination_vault.clone());
        account_infos.push(self.source_token_fees_vault.clone());
        account_infos.push(self.source_user_ata.clone());
        account_infos.push(self.destination_user_ata.clone());
        account_infos.push(self.source_token_program.clone());
        account_infos.push(self.destination_token_program.clone());
        if let Some(source_token_host_fees_account) = self.source_token_host_fees_account {
            account_infos.push(source_token_host_fees_account.clone());
        }
        if let Some(scope_price_feed) = self.scope_price_feed {
            account_infos.push(scope_price_feed.clone());
        }
        account_infos.push(self.event_authority.clone());
        account_infos.push(self.program.clone());
        remaining_accounts
            .iter()
            .for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

        if signers_seeds.is_empty() {
            solana_cpi::invoke(&instruction, &account_infos)
        } else {
            solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
        }
    }
}

/// Instruction builder for `Swap` via CPI.
///
/// ### Accounts:
///
///   0. `[writable, signer]` signer
///   1. `[writable]` pool
///   2. `[]` swap_curve
///   3. `[]` pool_authority
///   4. `[]` source_mint
///   5. `[]` destination_mint
///   6. `[writable]` source_vault
///   7. `[writable]` destination_vault
///   8. `[writable]` source_token_fees_vault
///   9. `[writable]` source_user_ata
///   10. `[writable]` destination_user_ata
///   11. `[]` source_token_program
///   12. `[]` destination_token_program
///   13. `[writable, optional]` source_token_host_fees_account
///   14. `[optional]` scope_price_feed
///   15. `[]` event_authority
///   16. `[]` program
#[derive(Clone, Debug)]
pub struct SwapCpiBuilder<'a, 'b> {
    instruction: Box<SwapCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> SwapCpiBuilder<'a, 'b> {
    pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
        let instruction = Box::new(SwapCpiBuilderInstruction {
            __program: program,
            signer: None,
            pool: None,
            swap_curve: None,
            pool_authority: None,
            source_mint: None,
            destination_mint: None,
            source_vault: None,
            destination_vault: None,
            source_token_fees_vault: None,
            source_user_ata: None,
            destination_user_ata: None,
            source_token_program: None,
            destination_token_program: None,
            source_token_host_fees_account: None,
            scope_price_feed: None,
            event_authority: None,
            program: None,
            amount_in: None,
            minimum_amount_out: None,
            __remaining_accounts: Vec::new(),
        });
        Self { instruction }
    }
    #[inline(always)]
    pub fn signer(&mut self, signer: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.signer = Some(signer);
        self
    }
    #[inline(always)]
    pub fn pool(&mut self, pool: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.pool = Some(pool);
        self
    }
    #[inline(always)]
    pub fn swap_curve(
        &mut self,
        swap_curve: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.swap_curve = Some(swap_curve);
        self
    }
    #[inline(always)]
    pub fn pool_authority(
        &mut self,
        pool_authority: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.pool_authority = Some(pool_authority);
        self
    }
    #[inline(always)]
    pub fn source_mint(
        &mut self,
        source_mint: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.source_mint = Some(source_mint);
        self
    }
    #[inline(always)]
    pub fn destination_mint(
        &mut self,
        destination_mint: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.destination_mint = Some(destination_mint);
        self
    }
    #[inline(always)]
    pub fn source_vault(
        &mut self,
        source_vault: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.source_vault = Some(source_vault);
        self
    }
    #[inline(always)]
    pub fn destination_vault(
        &mut self,
        destination_vault: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.destination_vault = Some(destination_vault);
        self
    }
    /// Account to collect fees into
    #[inline(always)]
    pub fn source_token_fees_vault(
        &mut self,
        source_token_fees_vault: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.source_token_fees_vault = Some(source_token_fees_vault);
        self
    }
    /// Signer's source token account
    #[inline(always)]
    pub fn source_user_ata(
        &mut self,
        source_user_ata: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.source_user_ata = Some(source_user_ata);
        self
    }
    /// Signer's destination token account
    #[inline(always)]
    pub fn destination_user_ata(
        &mut self,
        destination_user_ata: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.destination_user_ata = Some(destination_user_ata);
        self
    }
    /// Token program for the source mint
    #[inline(always)]
    pub fn source_token_program(
        &mut self,
        source_token_program: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.source_token_program = Some(source_token_program);
        self
    }
    /// Token program for the destination mint
    #[inline(always)]
    pub fn destination_token_program(
        &mut self,
        destination_token_program: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.destination_token_program = Some(destination_token_program);
        self
    }
    /// `[optional account]`
    /// Optional pool token fees account for front ends - if not present, all fees are sent to the trading fees account
    #[inline(always)]
    pub fn source_token_host_fees_account(
        &mut self,
        source_token_host_fees_account: Option<&'b solana_account_info::AccountInfo<'a>>,
    ) -> &mut Self {
        self.instruction.source_token_host_fees_account = source_token_host_fees_account;
        self
    }
    /// `[optional account]`
    /// Optional Scope price feed account (required for Oracle based curves)
    #[inline(always)]
    pub fn scope_price_feed(
        &mut self,
        scope_price_feed: Option<&'b solana_account_info::AccountInfo<'a>>,
    ) -> &mut Self {
        self.instruction.scope_price_feed = scope_price_feed;
        self
    }
    #[inline(always)]
    pub fn event_authority(
        &mut self,
        event_authority: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.event_authority = Some(event_authority);
        self
    }
    #[inline(always)]
    pub fn program(&mut self, program: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.program = Some(program);
        self
    }
    #[inline(always)]
    pub fn amount_in(&mut self, amount_in: u64) -> &mut Self {
        self.instruction.amount_in = Some(amount_in);
        self
    }
    #[inline(always)]
    pub fn minimum_amount_out(&mut self, minimum_amount_out: u64) -> &mut Self {
        self.instruction.minimum_amount_out = Some(minimum_amount_out);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(
        &mut self,
        account: &'b solana_account_info::AccountInfo<'a>,
        is_writable: bool,
        is_signer: bool,
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .push((account, is_writable, is_signer));
        self
    }
    /// Add additional accounts to the instruction.
    ///
    /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
    /// and a `bool` indicating whether the account is a signer or not.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .extend_from_slice(accounts);
        self
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed(&[])
    }
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        let args = SwapInstructionArgs {
            amount_in: self
                .instruction
                .amount_in
                .clone()
                .expect("amount_in is not set"),
            minimum_amount_out: self
                .instruction
                .minimum_amount_out
                .clone()
                .expect("minimum_amount_out is not set"),
        };
        let instruction = SwapCpi {
            __program: self.instruction.__program,

            signer: self.instruction.signer.expect("signer is not set"),

            pool: self.instruction.pool.expect("pool is not set"),

            swap_curve: self.instruction.swap_curve.expect("swap_curve is not set"),

            pool_authority: self
                .instruction
                .pool_authority
                .expect("pool_authority is not set"),

            source_mint: self
                .instruction
                .source_mint
                .expect("source_mint is not set"),

            destination_mint: self
                .instruction
                .destination_mint
                .expect("destination_mint is not set"),

            source_vault: self
                .instruction
                .source_vault
                .expect("source_vault is not set"),

            destination_vault: self
                .instruction
                .destination_vault
                .expect("destination_vault is not set"),

            source_token_fees_vault: self
                .instruction
                .source_token_fees_vault
                .expect("source_token_fees_vault is not set"),

            source_user_ata: self
                .instruction
                .source_user_ata
                .expect("source_user_ata is not set"),

            destination_user_ata: self
                .instruction
                .destination_user_ata
                .expect("destination_user_ata is not set"),

            source_token_program: self
                .instruction
                .source_token_program
                .expect("source_token_program is not set"),

            destination_token_program: self
                .instruction
                .destination_token_program
                .expect("destination_token_program is not set"),

            source_token_host_fees_account: self.instruction.source_token_host_fees_account,

            scope_price_feed: self.instruction.scope_price_feed,

            event_authority: self
                .instruction
                .event_authority
                .expect("event_authority is not set"),

            program: self.instruction.program.expect("program is not set"),
            __args: args,
        };
        instruction.invoke_signed_with_remaining_accounts(
            signers_seeds,
            &self.instruction.__remaining_accounts,
        )
    }
}

#[derive(Clone, Debug)]
struct SwapCpiBuilderInstruction<'a, 'b> {
    __program: &'b solana_account_info::AccountInfo<'a>,
    signer: Option<&'b solana_account_info::AccountInfo<'a>>,
    pool: Option<&'b solana_account_info::AccountInfo<'a>>,
    swap_curve: Option<&'b solana_account_info::AccountInfo<'a>>,
    pool_authority: Option<&'b solana_account_info::AccountInfo<'a>>,
    source_mint: Option<&'b solana_account_info::AccountInfo<'a>>,
    destination_mint: Option<&'b solana_account_info::AccountInfo<'a>>,
    source_vault: Option<&'b solana_account_info::AccountInfo<'a>>,
    destination_vault: Option<&'b solana_account_info::AccountInfo<'a>>,
    source_token_fees_vault: Option<&'b solana_account_info::AccountInfo<'a>>,
    source_user_ata: Option<&'b solana_account_info::AccountInfo<'a>>,
    destination_user_ata: Option<&'b solana_account_info::AccountInfo<'a>>,
    source_token_program: Option<&'b solana_account_info::AccountInfo<'a>>,
    destination_token_program: Option<&'b solana_account_info::AccountInfo<'a>>,
    source_token_host_fees_account: Option<&'b solana_account_info::AccountInfo<'a>>,
    scope_price_feed: Option<&'b solana_account_info::AccountInfo<'a>>,
    event_authority: Option<&'b solana_account_info::AccountInfo<'a>>,
    program: Option<&'b solana_account_info::AccountInfo<'a>>,
    amount_in: Option<u64>,
    minimum_amount_out: Option<u64>,
    /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
    __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}
