//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshDeserialize;
use borsh::BorshSerialize;

pub const WITHDRAW_FEES_DISCRIMINATOR: [u8; 8] = [198, 212, 171, 109, 144, 215, 174, 89];

/// Accounts.
#[derive(Debug)]
pub struct WithdrawFees {
    pub admin: solana_pubkey::Pubkey,

    pub pool: solana_pubkey::Pubkey,

    pub pool_authority: solana_pubkey::Pubkey,

    pub fees_mint: solana_pubkey::Pubkey,
    /// Fee vault to withdraw from
    pub fees_vault: solana_pubkey::Pubkey,
    /// Admin's token account to withdraw fees to
    pub admin_fees_ata: solana_pubkey::Pubkey,
    /// Token program for the fee token mint
    pub fees_token_program: solana_pubkey::Pubkey,

    pub event_authority: solana_pubkey::Pubkey,

    pub program: solana_pubkey::Pubkey,
}

impl WithdrawFees {
    pub fn instruction(
        &self,
        args: WithdrawFeesInstructionArgs,
    ) -> solana_instruction::Instruction {
        self.instruction_with_remaining_accounts(args, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::vec_init_then_push)]
    pub fn instruction_with_remaining_accounts(
        &self,
        args: WithdrawFeesInstructionArgs,
        remaining_accounts: &[solana_instruction::AccountMeta],
    ) -> solana_instruction::Instruction {
        let mut accounts = Vec::with_capacity(9 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new(self.admin, true));
        accounts.push(solana_instruction::AccountMeta::new(self.pool, false));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.pool_authority,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.fees_mint,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(self.fees_vault, false));
        accounts.push(solana_instruction::AccountMeta::new(
            self.admin_fees_ata,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.fees_token_program,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.event_authority,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.program,
            false,
        ));
        accounts.extend_from_slice(remaining_accounts);
        let mut data = WithdrawFeesInstructionData::new().try_to_vec().unwrap();
        let mut args = args.try_to_vec().unwrap();
        data.append(&mut args);

        solana_instruction::Instruction {
            program_id: crate::KDEX_ID,
            accounts,
            data,
        }
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct WithdrawFeesInstructionData {
    discriminator: [u8; 8],
}

impl WithdrawFeesInstructionData {
    pub fn new() -> Self {
        Self {
            discriminator: [198, 212, 171, 109, 144, 215, 174, 89],
        }
    }

    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
        borsh::to_vec(self)
    }
}

impl Default for WithdrawFeesInstructionData {
    fn default() -> Self {
        Self::new()
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct WithdrawFeesInstructionArgs {
    pub requested_pool_token_amount: u64,
}

impl WithdrawFeesInstructionArgs {
    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
        borsh::to_vec(self)
    }
}

/// Instruction builder for `WithdrawFees`.
///
/// ### Accounts:
///
///   0. `[writable, signer]` admin
///   1. `[writable]` pool
///   2. `[]` pool_authority
///   3. `[]` fees_mint
///   4. `[writable]` fees_vault
///   5. `[writable]` admin_fees_ata
///   6. `[]` fees_token_program
///   7. `[]` event_authority
///   8. `[]` program
#[derive(Clone, Debug, Default)]
pub struct WithdrawFeesBuilder {
    admin: Option<solana_pubkey::Pubkey>,
    pool: Option<solana_pubkey::Pubkey>,
    pool_authority: Option<solana_pubkey::Pubkey>,
    fees_mint: Option<solana_pubkey::Pubkey>,
    fees_vault: Option<solana_pubkey::Pubkey>,
    admin_fees_ata: Option<solana_pubkey::Pubkey>,
    fees_token_program: Option<solana_pubkey::Pubkey>,
    event_authority: Option<solana_pubkey::Pubkey>,
    program: Option<solana_pubkey::Pubkey>,
    requested_pool_token_amount: Option<u64>,
    __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl WithdrawFeesBuilder {
    pub fn new() -> Self {
        Self::default()
    }
    #[inline(always)]
    pub fn admin(&mut self, admin: solana_pubkey::Pubkey) -> &mut Self {
        self.admin = Some(admin);
        self
    }
    #[inline(always)]
    pub fn pool(&mut self, pool: solana_pubkey::Pubkey) -> &mut Self {
        self.pool = Some(pool);
        self
    }
    #[inline(always)]
    pub fn pool_authority(&mut self, pool_authority: solana_pubkey::Pubkey) -> &mut Self {
        self.pool_authority = Some(pool_authority);
        self
    }
    #[inline(always)]
    pub fn fees_mint(&mut self, fees_mint: solana_pubkey::Pubkey) -> &mut Self {
        self.fees_mint = Some(fees_mint);
        self
    }
    /// Fee vault to withdraw from
    #[inline(always)]
    pub fn fees_vault(&mut self, fees_vault: solana_pubkey::Pubkey) -> &mut Self {
        self.fees_vault = Some(fees_vault);
        self
    }
    /// Admin's token account to withdraw fees to
    #[inline(always)]
    pub fn admin_fees_ata(&mut self, admin_fees_ata: solana_pubkey::Pubkey) -> &mut Self {
        self.admin_fees_ata = Some(admin_fees_ata);
        self
    }
    /// Token program for the fee token mint
    #[inline(always)]
    pub fn fees_token_program(&mut self, fees_token_program: solana_pubkey::Pubkey) -> &mut Self {
        self.fees_token_program = Some(fees_token_program);
        self
    }
    #[inline(always)]
    pub fn event_authority(&mut self, event_authority: solana_pubkey::Pubkey) -> &mut Self {
        self.event_authority = Some(event_authority);
        self
    }
    #[inline(always)]
    pub fn program(&mut self, program: solana_pubkey::Pubkey) -> &mut Self {
        self.program = Some(program);
        self
    }
    #[inline(always)]
    pub fn requested_pool_token_amount(&mut self, requested_pool_token_amount: u64) -> &mut Self {
        self.requested_pool_token_amount = Some(requested_pool_token_amount);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
        self.__remaining_accounts.push(account);
        self
    }
    /// Add additional accounts to the instruction.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[solana_instruction::AccountMeta],
    ) -> &mut Self {
        self.__remaining_accounts.extend_from_slice(accounts);
        self
    }
    #[allow(clippy::clone_on_copy)]
    pub fn instruction(&self) -> solana_instruction::Instruction {
        let accounts = WithdrawFees {
            admin: self.admin.expect("admin is not set"),
            pool: self.pool.expect("pool is not set"),
            pool_authority: self.pool_authority.expect("pool_authority is not set"),
            fees_mint: self.fees_mint.expect("fees_mint is not set"),
            fees_vault: self.fees_vault.expect("fees_vault is not set"),
            admin_fees_ata: self.admin_fees_ata.expect("admin_fees_ata is not set"),
            fees_token_program: self
                .fees_token_program
                .expect("fees_token_program is not set"),
            event_authority: self.event_authority.expect("event_authority is not set"),
            program: self.program.expect("program is not set"),
        };
        let args = WithdrawFeesInstructionArgs {
            requested_pool_token_amount: self
                .requested_pool_token_amount
                .clone()
                .expect("requested_pool_token_amount is not set"),
        };

        accounts.instruction_with_remaining_accounts(args, &self.__remaining_accounts)
    }
}

/// `withdraw_fees` CPI accounts.
pub struct WithdrawFeesCpiAccounts<'a, 'b> {
    pub admin: &'b solana_account_info::AccountInfo<'a>,

    pub pool: &'b solana_account_info::AccountInfo<'a>,

    pub pool_authority: &'b solana_account_info::AccountInfo<'a>,

    pub fees_mint: &'b solana_account_info::AccountInfo<'a>,
    /// Fee vault to withdraw from
    pub fees_vault: &'b solana_account_info::AccountInfo<'a>,
    /// Admin's token account to withdraw fees to
    pub admin_fees_ata: &'b solana_account_info::AccountInfo<'a>,
    /// Token program for the fee token mint
    pub fees_token_program: &'b solana_account_info::AccountInfo<'a>,

    pub event_authority: &'b solana_account_info::AccountInfo<'a>,

    pub program: &'b solana_account_info::AccountInfo<'a>,
}

/// `withdraw_fees` CPI instruction.
pub struct WithdrawFeesCpi<'a, 'b> {
    /// The program to invoke.
    pub __program: &'b solana_account_info::AccountInfo<'a>,

    pub admin: &'b solana_account_info::AccountInfo<'a>,

    pub pool: &'b solana_account_info::AccountInfo<'a>,

    pub pool_authority: &'b solana_account_info::AccountInfo<'a>,

    pub fees_mint: &'b solana_account_info::AccountInfo<'a>,
    /// Fee vault to withdraw from
    pub fees_vault: &'b solana_account_info::AccountInfo<'a>,
    /// Admin's token account to withdraw fees to
    pub admin_fees_ata: &'b solana_account_info::AccountInfo<'a>,
    /// Token program for the fee token mint
    pub fees_token_program: &'b solana_account_info::AccountInfo<'a>,

    pub event_authority: &'b solana_account_info::AccountInfo<'a>,

    pub program: &'b solana_account_info::AccountInfo<'a>,
    /// The arguments for the instruction.
    pub __args: WithdrawFeesInstructionArgs,
}

impl<'a, 'b> WithdrawFeesCpi<'a, 'b> {
    pub fn new(
        program: &'b solana_account_info::AccountInfo<'a>,
        accounts: WithdrawFeesCpiAccounts<'a, 'b>,
        args: WithdrawFeesInstructionArgs,
    ) -> Self {
        Self {
            __program: program,
            admin: accounts.admin,
            pool: accounts.pool,
            pool_authority: accounts.pool_authority,
            fees_mint: accounts.fees_mint,
            fees_vault: accounts.fees_vault,
            admin_fees_ata: accounts.admin_fees_ata,
            fees_token_program: accounts.fees_token_program,
            event_authority: accounts.event_authority,
            program: accounts.program,
            __args: args,
        }
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], &[])
    }
    #[inline(always)]
    pub fn invoke_with_remaining_accounts(
        &self,
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
    }
    #[inline(always)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed_with_remaining_accounts(
        &self,
        signers_seeds: &[&[&[u8]]],
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        let mut accounts = Vec::with_capacity(9 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new(*self.admin.key, true));
        accounts.push(solana_instruction::AccountMeta::new(*self.pool.key, false));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.pool_authority.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.fees_mint.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.fees_vault.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.admin_fees_ata.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.fees_token_program.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.event_authority.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.program.key,
            false,
        ));
        remaining_accounts.iter().for_each(|remaining_account| {
            accounts.push(solana_instruction::AccountMeta {
                pubkey: *remaining_account.0.key,
                is_signer: remaining_account.1,
                is_writable: remaining_account.2,
            })
        });
        let mut data = WithdrawFeesInstructionData::new().try_to_vec().unwrap();
        let mut args = self.__args.try_to_vec().unwrap();
        data.append(&mut args);

        let instruction = solana_instruction::Instruction {
            program_id: crate::KDEX_ID,
            accounts,
            data,
        };
        let mut account_infos = Vec::with_capacity(10 + remaining_accounts.len());
        account_infos.push(self.__program.clone());
        account_infos.push(self.admin.clone());
        account_infos.push(self.pool.clone());
        account_infos.push(self.pool_authority.clone());
        account_infos.push(self.fees_mint.clone());
        account_infos.push(self.fees_vault.clone());
        account_infos.push(self.admin_fees_ata.clone());
        account_infos.push(self.fees_token_program.clone());
        account_infos.push(self.event_authority.clone());
        account_infos.push(self.program.clone());
        remaining_accounts
            .iter()
            .for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

        if signers_seeds.is_empty() {
            solana_cpi::invoke(&instruction, &account_infos)
        } else {
            solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
        }
    }
}

/// Instruction builder for `WithdrawFees` via CPI.
///
/// ### Accounts:
///
///   0. `[writable, signer]` admin
///   1. `[writable]` pool
///   2. `[]` pool_authority
///   3. `[]` fees_mint
///   4. `[writable]` fees_vault
///   5. `[writable]` admin_fees_ata
///   6. `[]` fees_token_program
///   7. `[]` event_authority
///   8. `[]` program
#[derive(Clone, Debug)]
pub struct WithdrawFeesCpiBuilder<'a, 'b> {
    instruction: Box<WithdrawFeesCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> WithdrawFeesCpiBuilder<'a, 'b> {
    pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
        let instruction = Box::new(WithdrawFeesCpiBuilderInstruction {
            __program: program,
            admin: None,
            pool: None,
            pool_authority: None,
            fees_mint: None,
            fees_vault: None,
            admin_fees_ata: None,
            fees_token_program: None,
            event_authority: None,
            program: None,
            requested_pool_token_amount: None,
            __remaining_accounts: Vec::new(),
        });
        Self { instruction }
    }
    #[inline(always)]
    pub fn admin(&mut self, admin: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.admin = Some(admin);
        self
    }
    #[inline(always)]
    pub fn pool(&mut self, pool: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.pool = Some(pool);
        self
    }
    #[inline(always)]
    pub fn pool_authority(
        &mut self,
        pool_authority: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.pool_authority = Some(pool_authority);
        self
    }
    #[inline(always)]
    pub fn fees_mint(&mut self, fees_mint: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.fees_mint = Some(fees_mint);
        self
    }
    /// Fee vault to withdraw from
    #[inline(always)]
    pub fn fees_vault(
        &mut self,
        fees_vault: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.fees_vault = Some(fees_vault);
        self
    }
    /// Admin's token account to withdraw fees to
    #[inline(always)]
    pub fn admin_fees_ata(
        &mut self,
        admin_fees_ata: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.admin_fees_ata = Some(admin_fees_ata);
        self
    }
    /// Token program for the fee token mint
    #[inline(always)]
    pub fn fees_token_program(
        &mut self,
        fees_token_program: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.fees_token_program = Some(fees_token_program);
        self
    }
    #[inline(always)]
    pub fn event_authority(
        &mut self,
        event_authority: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.event_authority = Some(event_authority);
        self
    }
    #[inline(always)]
    pub fn program(&mut self, program: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.program = Some(program);
        self
    }
    #[inline(always)]
    pub fn requested_pool_token_amount(&mut self, requested_pool_token_amount: u64) -> &mut Self {
        self.instruction.requested_pool_token_amount = Some(requested_pool_token_amount);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(
        &mut self,
        account: &'b solana_account_info::AccountInfo<'a>,
        is_writable: bool,
        is_signer: bool,
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .push((account, is_writable, is_signer));
        self
    }
    /// Add additional accounts to the instruction.
    ///
    /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
    /// and a `bool` indicating whether the account is a signer or not.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .extend_from_slice(accounts);
        self
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed(&[])
    }
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        let args = WithdrawFeesInstructionArgs {
            requested_pool_token_amount: self
                .instruction
                .requested_pool_token_amount
                .clone()
                .expect("requested_pool_token_amount is not set"),
        };
        let instruction = WithdrawFeesCpi {
            __program: self.instruction.__program,

            admin: self.instruction.admin.expect("admin is not set"),

            pool: self.instruction.pool.expect("pool is not set"),

            pool_authority: self
                .instruction
                .pool_authority
                .expect("pool_authority is not set"),

            fees_mint: self.instruction.fees_mint.expect("fees_mint is not set"),

            fees_vault: self.instruction.fees_vault.expect("fees_vault is not set"),

            admin_fees_ata: self
                .instruction
                .admin_fees_ata
                .expect("admin_fees_ata is not set"),

            fees_token_program: self
                .instruction
                .fees_token_program
                .expect("fees_token_program is not set"),

            event_authority: self
                .instruction
                .event_authority
                .expect("event_authority is not set"),

            program: self.instruction.program.expect("program is not set"),
            __args: args,
        };
        instruction.invoke_signed_with_remaining_accounts(
            signers_seeds,
            &self.instruction.__remaining_accounts,
        )
    }
}

#[derive(Clone, Debug)]
struct WithdrawFeesCpiBuilderInstruction<'a, 'b> {
    __program: &'b solana_account_info::AccountInfo<'a>,
    admin: Option<&'b solana_account_info::AccountInfo<'a>>,
    pool: Option<&'b solana_account_info::AccountInfo<'a>>,
    pool_authority: Option<&'b solana_account_info::AccountInfo<'a>>,
    fees_mint: Option<&'b solana_account_info::AccountInfo<'a>>,
    fees_vault: Option<&'b solana_account_info::AccountInfo<'a>>,
    admin_fees_ata: Option<&'b solana_account_info::AccountInfo<'a>>,
    fees_token_program: Option<&'b solana_account_info::AccountInfo<'a>>,
    event_authority: Option<&'b solana_account_info::AccountInfo<'a>>,
    program: Option<&'b solana_account_info::AccountInfo<'a>>,
    requested_pool_token_amount: Option<u64>,
    /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
    __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}
