//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshDeserialize;
use borsh::BorshSerialize;
use solana_pubkey::Pubkey;

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub enum CurveUserParameters {
    ConstantProduct,
    ConstantPrice {
        token_b_price: u64,
    },
    Offset {
        token_b_offset: u64,
    },
    Stable {
        amp: u64,
    },
    ConstantSpreadOracle {
        #[cfg_attr(
            feature = "serde",
            serde(with = "serde_with::As::<serde_with::DisplayFromStr>")
        )]
        scope_price_feed: Pubkey,
        /// Price chain - array of Scope price indices (up to 4)
        /// Values of u16::MAX (65535) terminate the chain
        /// Example: [387, 0, MAX, MAX] = bonkSOL/SOL * SOL/USD
        price_chain: [u16; 4],
        /// Max age in seconds for each price index in the chain
        max_age_secs: [u16; 4],
        bps_from_oracle: u64,
    },
    InventorySkewOracle {
        #[cfg_attr(
            feature = "serde",
            serde(with = "serde_with::As::<serde_with::DisplayFromStr>")
        )]
        scope_price_feed: Pubkey,
        /// Price chain - array of Scope price indices (up to 4)
        /// Values of u16::MAX (65535) terminate the chain
        price_chain: [u16; 4],
        /// Max age in seconds for each price index in the chain
        max_age_secs: [u16; 4],
        base_spread_bps: u64,
        size_spread_bps: u64,
        skew_bps: u64,
        inv_equilibrium: u64,
        inv_max: u64,
        q_ref: u64,
        alpha: u64,
    },
}
