//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

pub(crate) mod r#curve_user_parameters;
pub(crate) mod r#deposit;
pub(crate) mod r#fees;
pub(crate) mod r#price_chain_fetched;
pub(crate) mod r#swap;
pub(crate) mod r#update_pool_config;
pub(crate) mod r#update_pool_config_mode;
pub(crate) mod r#update_pool_config_value;
pub(crate) mod r#withdraw;
pub(crate) mod r#withdraw_fees;

pub use self::r#curve_user_parameters::*;
pub use self::r#deposit::*;
pub use self::r#fees::*;
pub use self::r#price_chain_fetched::*;
pub use self::r#swap::*;
pub use self::r#update_pool_config::*;
pub use self::r#update_pool_config_mode::*;
pub use self::r#update_pool_config_value::*;
pub use self::r#withdraw::*;
pub use self::r#withdraw_fees::*;
