//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshDeserialize;
use borsh::BorshSerialize;
use solana_pubkey::Pubkey;

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct PriceChainFetched {
    /// The pool using this price chain
    #[cfg_attr(
        feature = "serde",
        serde(with = "serde_with::As::<serde_with::DisplayFromStr>")
    )]
    pub pool: Pubkey,
    /// Number of prices in the chain (1-4)
    pub chain_length: u8,
    /// Price indices used [index0, index1, index2, index3]
    pub price_indices: [u16; 4],
    /// Price values [value0, value1, value2, value3]
    pub price_values: [u64; 4],
    /// Price exponents [exp0, exp1, exp2, exp3]
    pub price_exponents: [u64; 4],
    /// Timestamps [ts0, ts1, ts2, ts3]
    pub price_timestamps: [u64; 4],
    /// Combined price value after multiplication
    pub combined_value: u128,
    /// Combined price exponent after addition
    pub combined_exponent: u64,
}
