//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use num_derive::FromPrimitive;
use thiserror::Error;

#[derive(Clone, Debug, Eq, Error, FromPrimitive, PartialEq)]
pub enum KdexError {
    /// 6000 - Invalid program address generated from bump seed and key
    #[error("Invalid program address generated from bump seed and key")]
    InvalidProgramAddress = 0x1770,
    /// 6001 - Input token account empty
    #[error("Input token account empty")]
    EmptySupply = 0x1771,
    /// 6002 - Address of the provided swap token account is incorrect
    #[error("Address of the provided swap token account is incorrect")]
    IncorrectSwapAccount = 0x1772,
    /// 6003 - Address of the provided pool token mint is incorrect
    #[error("Address of the provided pool token mint is incorrect")]
    IncorrectPoolMint = 0x1773,
    /// 6004 - General calculation failure due to overflow or underflow
    #[error("General calculation failure due to overflow or underflow")]
    CalculationFailure = 0x1774,
    /// 6005 - Swap input token accounts have the same mint
    #[error("Swap input token accounts have the same mint")]
    RepeatedMint = 0x1775,
    /// 6006 - Swap instruction exceeds desired slippage limit
    #[error("Swap instruction exceeds desired slippage limit")]
    ExceededSlippage = 0x1776,
    /// 6007 - Token account has a close authority
    #[error("Token account has a close authority")]
    InvalidCloseAuthority = 0x1777,
    /// 6008 - Pool token mint has a freeze authority
    #[error("Pool token mint has a freeze authority")]
    InvalidFreezeAuthority = 0x1778,
    /// 6009 - Pool fee token account incorrect
    #[error("Pool fee token account incorrect")]
    IncorrectFeeAccount = 0x1779,
    /// 6010 - Given pool token amount results in zero trading tokens
    #[error("Given pool token amount results in zero trading tokens")]
    ZeroTradingTokens = 0x177A,
    /// 6011 - Fee calculation failed due to overflow, underflow, or unexpected 0
    #[error("Fee calculation failed due to overflow, underflow, or unexpected 0")]
    FeeCalculationFailure = 0x177B,
    /// 6012 - Conversion to u64 failed with an overflow or underflow
    #[error("Conversion to u64 failed with an overflow or underflow")]
    ConversionFailure = 0x177C,
    /// 6013 - The provided fee does not match the program owner's constraints
    #[error("The provided fee does not match the program owner's constraints")]
    InvalidFee = 0x177D,
    /// 6014 - The provided curve type is not supported by the program owner
    #[error("The provided curve type is not supported by the program owner")]
    UnsupportedCurveType = 0x177E,
    /// 6015 - The provided curve parameters are invalid
    #[error("The provided curve parameters are invalid")]
    InvalidCurve = 0x177F,
    /// 6016 - The operation cannot be performed on the given curve
    #[error("The operation cannot be performed on the given curve")]
    UnsupportedCurveOperation = 0x1780,
    /// 6017 - The operation cannot be performed because the pool is in withdrawals only mode
    #[error("The operation cannot be performed because the pool is in withdrawals only mode")]
    WithdrawalsOnlyMode = 0x1781,
    /// 6018 - Address of the provided trading token mint is incorrect
    #[error("Address of the provided trading token mint is incorrect")]
    IncorrectTradingMint = 0x1782,
    /// 6019 - Insufficient funds in the pool token account
    #[error("Insufficient funds in the pool token account")]
    InsufficientPoolTokenFunds = 0x1783,
    /// 6020 - Pool admin is not correct
    #[error("Pool admin is not correct")]
    InvaliPoolAdmin = 0x1784,
    /// 6021 - Token 2022 extension is not supported
    #[error("Token 2022 extension is not supported")]
    InvalidTokenExtension = 0x1785,
    /// 6022 - Invalid oracle configuration
    #[error("Invalid oracle configuration")]
    InvalidOracleConfig = 0x1786,
    /// 6023 - Invalid oracle price feed
    #[error("Invalid oracle price feed")]
    InvalidOraclePriceFeed = 0x1787,
    /// 6024 - Invalid oracle price
    #[error("Invalid oracle price")]
    InvalidOraclePrice = 0x1788,
    /// 6025 - Oracle price is too old
    #[error("Oracle price is too old")]
    OraclePriceTooOld = 0x1789,
}

impl From<KdexError> for solana_program_error::ProgramError {
    fn from(e: KdexError) -> Self {
        solana_program_error::ProgramError::Custom(e as u32)
    }
}
