//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use solana_pubkey::{pubkey, Pubkey};

/// `hyperplane` program ID.
pub const HYPERPLANE_ID: Pubkey = pubkey!("kdexv89r17wFQN1MY3auCX7QgWFyshWAji2LsLRVUQU");
